### ISSUE TITLE
Problem minting on localnet

### ISSUE THREAD

**Issue by JockDaRock** [samuelvanderwaal/metaboss#102]
I am running a local solana validator node (127.0.0.1:8899). I cannot seem to get this command to work:

```
metaboss mint one --keypair <keypair-file-path> --nft-data-file <data-file.json> --sign
```

the result of running the metaboss minut command is the following:

```
Error: RPC response error -32002: Transaction simulation failed: Attempt to load a program that does not exist
```

I was able to get it to work on devnet, but not on localnet as of yet.

Probably a total noob question, but what am I doing wrong here? And what do I need to do to fix it?

**Comment by poisendev91** [comment]
Use custom rpc
Here is one
https://ssc-dao.genesysgo.net/
Join my discord to get more help
[THIRD EYE](https://discord.gg/UurzmJW3bC)

**Comment by JockDaRock** [comment]
Thank you @poisendev91, but I would actually like to see the process of loading a program up to a Solana node, at least one that is more complex than the hello world I have seen. and to also be able to do this on a Solana node I control.

I see on the Solana docs where you have to have a binary in a *.so filetype. Is there something that needs to be loaded and compiled for metaboss to then load the program smart contract up to the local solana node? that part is a bit unclear to me.

**Comment by JockDaRock** [comment]
As a follow on... I have tried using the `cargo build-bpf` command which is used in the solana-labs hello world example for metaboss, but I was not able to get that to build correctly.

**Comment by samuelvanderwaal** [comment]
> I am running a local solana validator node (127.0.0.1:8899). I cannot seem to get this command to work:
> 
> ```
> metaboss mint one --keypair <keypair-file-path> --nft-data-file <data-file.json> --sign
> ```
> 
> the result of running the metaboss minut command is the following:
> 
> ```
> Error: RPC response error -32002: Transaction simulation failed: Attempt to load a program that does not exist
> ```
> 
> I was able to get it to work on devnet, but not on localnet as of yet.
> 
> Probably a total noob question, but what am I doing wrong here? And what do I need to do to fix it?

You have to clone the `token-metadata` program to your localnet as Metaboss is calling that program to mint. Look up the `solana-test-validator` command's "clone" option.

**Comment by samuelvanderwaal** [comment]
> As a follow on... I have tried using the `cargo build-bpf` command which is used in the solana-labs hello world example, but I adapted for metaboss, but I was not able to get that to build correctly.

`cargo build-bpf` is for compiling Solana programs (smart contracts). Metaboss isn't an on-chain program, it runs client side and makes calls to the `token-metadata` program which *is* on-chain.

**Comment by samuelvanderwaal** [comment]
@JockDaRock did this resolve your issue?

**Comment by JockDaRock** [comment]
@samuelvanderwaal Thank you for your help. Sorry for the slow reply. Was on vacation last week and didn't have a chance to finish testing before then. 

I think this resolves my issue for now. More and more I am looking into the process of running nodes, but that is more for the Solana network than for metaboss.

all that said, I love metaboss and I have really enjoyed your work on it!
closing this issue.
