### ISSUE TITLE
Sign all command broken

### ISSUE THREAD

**Issue by AnderUstarroz** [samuelvanderwaal/metaboss#104]
Something seems to be wrong with the latest version (**Metaboss v0.5.1**). I have installed the latest via `cargo install metaboss`:

```
    Replaced package `metaboss v0.4.0-beta (~/metaboss)` with `metaboss v0.5.1 (~/metaboss)` (executable `metaboss`)
```

But now when if I try to sign my NFT:
```
metaboss sign all -k ~/.config/solana/my_key.json --candy-machine-id MY_CM2_ID --v2
```
 I got the following error:
```error: Found argument '--candy-machine-id' which wasn't expected, or isn't valid in this context```
and if I remove that param `--candy-machine-id` I got this:
```
Error: Must specify exactly one of --candy-machine-id or --mint-data-dir
```

**Comment by AnderUstarroz** [comment]
function seems to be changed, now uses the param `--creator`  where I suppose we need to add the first Creator address of an NFT created by the CM2. So I think this issue should be just about updating the docs.

**Comment by samuelvanderwaal** [comment]
> function seems to be changed, now uses the param `--creator` where I suppose we need to add the first Creator address of an NFT created by the CM2. So I think this issue should be just about updating the docs.

Yeah, I just hadn't updated the docs. Pushed an update just now. Thanks for the heads up.

**Comment by AnderUstarroz** [comment]
Why changed from  candy machine ID to `creator`?  isn't it confusing?  people may try to use the NFT `creator` field (which can be spoofed) when is actually the Candy Machine ID what should be used.

**Comment by samuelvanderwaal** [comment]
> Why changed from candy machine ID to `creator`? isn't it confusing? people may try to use the NFT `creator` field (which can be spoofed) when is actually the Candy Machine ID what should be used.

This is just a more accurate description of what was already happening. `snapshot` checks by first verified creator in the creators array to find NFTs. For NFTs minted with a candy machine that is the candy machine ID by default, but it doesn't have to be. Creators can be spoofed but verified creators can't so that's why it checks that the creator is verified.
