### ISSUE TITLE
cannot update on-chain metadata

### ISSUE THREAD

**Issue by felixxcheng** [samuelvanderwaal/metaboss#106]
`
metaboss update data --keypair superduper.json --account 2MeoFQTcfFovnYVjbMVeEyXbVZEpv9UQFY9rzDZ5vQdU --new-data-file 2MeoFQTcfFovnYVjbMVeEyXbVZEpv9UQFY9rzDZ5vQdU.json
`

getting:
`
Error: missing field `name` at line 34 column 1
`

I haven't found any particular great examples of all the on-chain metadata fields so I just grabbed all the solscan.io data:
`
"root": {
    9 items
    "key":int4
    "updateAuthority":string"5TQsnMGXUqukFBMsJyy93TsHbN4ncWfSHdD4VoCvD5XB"
    "mint":string"2MeoFQTcfFovnYVjbMVeEyXbVZEpv9UQFY9rzDZ5vQdU"
    "data": {
        5 items
    "name":string"SYMBOLIKA #0"
    "symbol":string"SYM"
    "uri":string"https://czedhzn7prmzqzocey2hajkut3vzczr5sj2azq7ljuom4wcdom.arweave.net/Fkgz5b98WZhlwiY0cCVUnuuRZj2SdAz_D600czlhDc0"
    "sellerFeeBasisPoints":int2000
    "creators": [
            2 items
    0: {
                3 items
    "address":string"e1Z9WY6oaRc49kufJuuK9TndLJjxCWnjUgh6Ep3Jpt1"
    "verified":int1
    "share":int0
            }
    1: {
                3 items
    "address":string"BgfMkBCbMqYHM9gAhzrTGQSAhhzBHV9icXn4zKgYbJE"
    "verified":int0
    "share":int100
            }
        ]
    }
    "primarySaleHappened":int1
    "isMutable":int1
    "editionNonce":int247
    "type":string"metaplex"
    "edition": {
        3 items
    "type":string"MasterEdition"
    "maxSupply":string"0"
    "supply":string"0"
    }
}
`

then tried to duplicate it like so:
`
{
    "key": "MetadataV1",
    "update_authority": "5TQsnMGXUqukFBMsJyy93TsHbN4ncWfSHdD4VoCvD5XB",
    "mint": "2MeoFQTcfFovnYVjbMVeEyXbVZEpv9UQFY9rzDZ5vQdU",
    
    "data": {
        "name": "SYMBOLIKA #0",
        "seller_fee_basis_points": 2000,
        "symbol": "SYM",
        "uri": "https://czedhzn7prmzqzocey2hajkut3vzczr5sj2azq7ljuom4wcdom.arweave.net/Fkgz5b98WZhlwiY0cCVUnuuRZj2SdAz_D600czlhDc0",
        "creators": [
            {
                "address": "e1Z9WY6oaRc49kufJuuK9TndLJjxCWnjUgh6Ep3Jpt1",
                "share": 0,
                "verified": true
            },
            {
                "address": "DK4oSneetEucg4fxgCBCSg4nhZx5DHGK8C3u4MCtPDoz",
                "share": 100,
                "verified": false
            }
        ]
    },
    "primary_sale_happened": true,
    "is_mutable": true,
    "edition_nonce": 247,
    "type": "metaplex",
    "edition": {
        "type":"MasterEdition",
        "maxSupply":"0",
        "supply":"0"
    },
    "original_uri":"https://bafkreig7rpgibsjiyu5mwwwcta3jiegmvwsgodi65jifvb3vqorlsaujxy.ipfs.dweb.link/"
}
`

please tell me a better way of going about this.  Thank you

**Comment by samuelvanderwaal** [comment]
The docs have an example: https://metaboss.rs/update.html

**Comment by samuelvanderwaal** [comment]
There's also the Metaplex docs describing the standard: https://docs.metaplex.com/architecture/deep_dive/overview

**Comment by felixxcheng** [comment]
Sir, instead of just filling all structs, i took this from your site without any deviation, and just adjusted the fields to my needs.  It worked!  Thank you for creating such a wonderful tool.

`
{
    "name": "FerrisCrab #4",
    "symbol": "FERRIS",
    "uri": "https://arweave.net/N36gZYJ6PEH8OE11i0MppIbPG4VXKV4iuQw1zaq3rls",
    "seller_fee_basis_points": 100,
    "creators": [
        {
            "address": "<YOUR_CANDY_MACHINE_ID>",
            "verified": true,
            "share": 0
        },
        {
            "address": "<KEYPAIR_CREATOR>",
            "verified": true,
            "share": 50
        },
        {
            "address": "42NevAWA6A8m9prDvZRUYReQmhNC3NtSZQNFUppPJDRB",
            "verified": false,
            "share": 50
        }
    ]
}
`
