### ISSUE TITLE
Issue with QuickNode persisting?

### ISSUE THREAD

**Issue by ck256-2000** [samuelvanderwaal/metaboss#109]
Am having a heckuva time getting Metaboss to give me back snapshots off mainnet-beta. Here's the ID - I'm just trying to get holders: CcYPTdUqULeubvdDtgkYVqbtHe2wZusxaqQ4XSe1vTAD

Get time out - when switching over to regular api - I get the 410 errors as well.

Great tool and I have some really good use cases for it.  Willing to pay for support :)

**Comment by ck256-2000** [comment]
so.... I pushed the time out -t 180 and am getting back results.  man, this'll be rough if they can't get this figured out.

**Comment by ck256-2000** [comment]
oh, and feel free to close - still a great product - thanks for dev - start selling NFT's for support boss! ;)

**Comment by samuelvanderwaal** [comment]
Yeah, this is a Solana and Metaplex issue with the growing size of the number of accounts owned by `token-metadata` making `getProgramAccounts` calls slower and slower. I'm investigating ways to do this differently and make it faster but everything has trade-offs and drawbacks.

**Comment by samuelvanderwaal** [comment]
> Get time out - when switching over to regular api - I get the 410 errors as well.

Public Solana APIs completely block `getProgramAccounts` calls on the `token-metadata` program so these won't work for `snapshot` commands at all now.
