### ISSUE TITLE
Request: Create MasterEditions with max_supply > 0 and mint copies

### ISSUE THREAD

**Issue by znebby** [samuelvanderwaal/metaboss#124]
Sometimes NFTs have a set number of copies, or some are even unlimited. Metaplex supports this use case.

We need to be able to create a MasterEdition, and then mint copies of a specific MasterEdition.

**Comment by samuelvanderwaal** [comment]
@znebby 
This is not documented yet but is supported in 0.6.0+ with:

`metaboss mint one --max-editions <int>`

`metaboss mint editions`
 -- either mint the next n editions sequentially using --next-editions <int> 
OR
-- mint specific edition numbers using --specific-editions <int> <int> <int>

`metaboss find missing-editions`
-- find any missing edition numbers in the sequential list of ones already minted

`metaboss mint missing-editions`
--find any missing edition numbers and mint them to the authority keypair

**Comment by samuelvanderwaal** [comment]
@znebby this is documented now and infinite editions are also supported. Let me know if you have any issues with it.
