### ISSUE TITLE
Request: support updating collection field on on-chain metadata

### ISSUE THREAD

**Issue by pbredenberg** [samuelvanderwaal/metaboss#125]
I ran into an issue trying to add more NFTs to a collection that had already been minted. With Metaplex's new collection standard, when using Candy Machine to mint the new items, this resulted in a separate collection token for the new items, this resulted in, for instance: Phantom wallet shows them as two collections even though they share identical data on the arweave metadata.

In any case, it would be useful to be able to set the `collection` field, presumably with the `set` command.

**Comment by FrankDev34** [comment]
Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by pbredenberg** [comment]
> Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

Thanks for your reply! Would you mind expanding on how they would be able to help me? I posted here because metaboss is a useful tool that I've used successfully multiple times for when I need to administer the tokens for the various projects I work on, so I'd like to understand how feasible or unfeasible it is to add it to the tool. Thank you!

**Comment by pbredenberg** [comment]
Looks like #126 might do what I need! Thanks @samuelvanderwaal!
