### ISSUE TITLE
Update all symbols

### ISSUE THREAD

**Issue by soulmv** [samuelvanderwaal/metaboss#130]
Hi,
Is it possible to update nft symbol on multiple mints?
Many thanks!

**Comment by samuelvanderwaal** [comment]
There's no `update symbol all` command yet but you can accomplish this (with extra effort) with the `update data all` command. I'll probably add `update symbol all`, `update creators all` commands, but it's lower priority over some other big refactors I'm working on.

**Comment by samuelvanderwaal** [comment]
This is now supported in v0.8.0.
