### ISSUE TITLE
update uri error

### ISSUE THREAD

**Issue by PapaBambinoman** [samuelvanderwaal/metaboss#139]
trying to fix broken uri for my one NFT 
but keep getting this error

I use command  metaboss.exe update uri [OPTIONS] --account <account> --new-uri <new-uri>

but nothing 

[2022-06-03T02:41:53Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
Error: RPC response error -32002: Transaction simulation failed: Blockhash not found 

Caused by:

**Comment by samuelvanderwaal** [comment]
This is a Solana issue with the cluster time. Hopefully it's fixed soon.
