### ISSUE TITLE
Install did not work - ~/.cargo/bin/metaboss: line 1: Not: command not found

### ISSUE THREAD

**Issue by numisman** [samuelvanderwaal/metaboss#140]
I tried installing by using the recommended command:

```bash <(curl -sSf https://raw.githubusercontent.com/samuelvanderwaal/metaboss/main/scripts/install.sh)```

Seemed to work fine:  

Metaboss CLI binary installation script
---------------------------------------

1. 🖥  Downloading distribution

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     38      0 --:--:-- --:--:-- --:--:--    38

2. 📤 Moving binary into place

Metaboss binary was found at:
  => ~/.cargo/bin/metaboss

Replace it? [Y/n] (default 'n'): Y

'metaboss' binary will be moved to '~/.cargo/bin'.

✅ Installation successful: type 'metaboss' to start using it.

I typed metaboss, and got 
~/.cargo/bin/metaboss: line 1: Not: command not found

--------------------------------

So....what gives?  I would prefer for sure to run a build script like this rather than get a compiled version (but THANKS KARTIK!)

**Comment by samuelvanderwaal** [comment]
> I tried installing by using the recommended command:
> 
> `bash <(curl -sSf https://raw.githubusercontent.com/samuelvanderwaal/metaboss/main/scripts/install.sh)`
> 
> Seemed to work fine:
> 
> ## Metaboss CLI binary installation script
> 1. 🖥  Downloading distribution
> 
> % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 9 100 9 0 0 38 0 --:--:-- --:--:-- --:--:-- 38
> 
> 2. 📤 Moving binary into place
> 
> Metaboss binary was found at: => ~/.cargo/bin/metaboss
> 
> Replace it? [Y/n] (default 'n'): Y
> 
> 'metaboss' binary will be moved to '~/.cargo/bin'.
> 
> ✅ Installation successful: type 'metaboss' to start using it.
> 
> I typed metaboss, and got ~/.cargo/bin/metaboss: line 1: Not: command not found
> 
> So....what gives? I would prefer for sure to run a build script like this rather than get a compiled version (but THANKS KARTIK!)

What OS is this?

**Comment by numisman** [comment]
Ubuntu

**Comment by samuelvanderwaal** [comment]
> Ubuntu

Is the file actually there? `ls ~/.cargo/bin`

**Comment by numisman** [comment]
Yes.  It was there at the time.

**Comment by numisman** [comment]
And 'which metaboss' reported correctly.

**Comment by samuelvanderwaal** [comment]
@numisman It should be fixed now. Can you try running the install script again and let me know if it works now for you?

**Comment by numisman** [comment]
Yeah - that did the trick!  What was the problem?

**Comment by samuelvanderwaal** [comment]
> Yeah - that did the trick! What was the problem?

The Ubuntu version name was wrong in the install script so it wasn't actually downloading the binary.

**Comment by numisman** [comment]
Thanks for the quick response!
