### ISSUE TITLE
RPC response error -32012: Node detected it replayed bad version of slot 138672000 with id 727281, thus the scan on said slot was aborted 

### ISSUE THREAD

**Issue by bowie-tey** [samuelvanderwaal/metaboss#141]
Using this command
`metaboss snapshot holders --creator <CREATOR_ADDRESS> -p <POSITION> --output <OUTPUT_DIR>`

However I keep running into the RPC error listed above, is this because I'm not using a private RPC

**Comment by PapaBambinoman** [comment]
Had same issue when running sign all

**Comment by samuelvanderwaal** [comment]
These are probably Solana issues. The cluster time has been multiple hours behind actual time for a while.
