### ISSUE TITLE
change update_authority for all

### ISSUE THREAD

**Issue by MukulGari** [samuelvanderwaal/metaboss#148]
In my candy machine v2 mint of 1000 nft i have given update authority to 2 account address and 1 is an hardware wallet and i wanna revoke it's authority from all of them. is their anything available for that in metaboss similarly to 
metaboss set update-authority-all --keypair <PATH_TO_KEYPAIR> --mint-accounts-file <PATH_TO_MINT_ACCOUNTS> --new-update-authority <NEW_UPDATE_AUTHORITY>
for hardware wallets
As solana cli allows to put wallet_url instead of keypair, does this work here too

**Comment by MukulGari** [comment]
any updates @samuelvanderwaal

**Comment by MukulGari** [comment]
any updates @samuelvanderwaal

**Comment by samuelvanderwaal** [comment]
I haven't had a chance to look into hardware wallet integration. Is it even possible to do a sign-all command with it without having to manually approve each transaction on the device?

**Comment by MukulGari** [comment]
Umm, yeah that's also my concern, if u can suggest how to add the integration part as solana cli allows to put wallet_url instead of keypair, and if we use the update-all sub-command and pass wallet url instead of <path_to_keypair>. & then mostly we have to approve only once, can u plz check or suggest something here.

ref. https://docs.solana.com/wallet-guide/hardware-wallets#:~:text=Solana%20defines%20a%20keypair%20URL,wallet%20connected%20to%20your%20computer.&text=WALLET_ID%20is%20a%20globally%20unique,keys%20within%20your%20hardware%20wallet.

**Comment by samuelvanderwaal** [comment]
I spent a little time implementing Ledger support and it was really flaky on my machine and there's still the issue of having to approve manually for every tx. I might try again some other time.
