### ISSUE TITLE
update data-all issues/ update creators-all suggestion

### ISSUE THREAD

**Issue by devtonic0** [samuelvanderwaal/metaboss#153]
I have been trying to update creators for a bit, i notice you dont have an option to run update creators-all and using that method would be 1 by 1. 

so I decoded onchain metadata and then changed out the creator that receives royalties, went to update and got an error for not having mint IDs (another recommendation is the option to use name for mint ID since thats where it is after decoding). I ran 1 single update to test it out with just the 100% royalties wallet changed out, nothing changed on chain despite the argument saying done!

**Comment by samuelvanderwaal** [comment]
> I have been trying to update creators for a bit, i notice you dont have an option to run update creators-all and using that method would be 1 by 1.
> 
> so I decoded onchain metadata and then changed out the creator that receives royalties, went to update and got an error for not having mint IDs (another recommendation is the option to use name for mint ID since thats where it is after decoding). I ran 1 single update to test it out with just the 100% royalties wallet changed out, nothing changed on chain despite the argument saying done!

I have plans to add `update creators-all` but in the meantime you have a couple options:

1) You can use `metaboss update creators` and loop over that command with a bash script or wrap it in another script using e.g. Python or Node.

2) Use `update data all` and only change the creators array. The easiest way to do this will be to get all the current data values with `metaboss decode mint -L <MINT_LIST_FILE> --full` to get a list of JSON files for each of your NFTs. Then you can update all the creators in each file and run `metaboss update data-all -d <DIR_OF_MODIFIED_JSON_FILES>`.

**Comment by devtonic0** [comment]
Thank you so much for your response! i see what i missed was the --full command. I really appreciate the quick response
