### ISSUE TITLE
All instructions on website are outdated. 

### ISSUE THREAD

**Issue by Lord-Satchel** [samuelvanderwaal/metaboss#154]
You can no longer update name, symbol and creators. 
big tip ?
after installing metaboss just go to help and see what ois available and what is not

**Comment by samuelvanderwaal** [comment]
> You can no longer update name, symbol and creators. big tip ? after installing metaboss just go to help and see what ois available and what is not

What version of Metaboss are you running? The website instructions are-up-to-date for v0.7.3. You probably installed an old version somehow. Check the version `metaboss -V` and make sure it's the latest one, and if not use the install script in the README to install the newest version.

**Comment by samuelvanderwaal** [comment]
@Lord-Satchel did this resolve your issue?

**Comment by Lord-Satchel** [comment]
yes thank you
