### ISSUE TITLE
snapshot candy machine mint accounts in correct order of mint

### ISSUE THREAD

**Issue by babyjackdoge** [samuelvanderwaal/metaboss#155]
Hello!

I would like to ask, is that possible to snapshot mint accounts in correct order of mint?

Thanks.

**Comment by samuelvanderwaal** [comment]
I don't think this is easy or possible to do with the way I'm currently getting the mint accounts. I think this would require transaction crawling to find the transaction each mint account was processed in and the slot of that transaction, and then ordering that way. I have it in mind as a nice-to-have down the road but is a pretty low priority for me right now.
