### ISSUE TITLE
mint holderst snapshot is time outing

### ISSUE THREAD

**Issue by nukec** [samuelvanderwaal/metaboss#158]
when i run following command:
`metaboss snapshot holders --creator mint_hash --output holders --v2`

i am constantly getting time out no matter which paid rpc i use. is there a change?

**Comment by samuelvanderwaal** [comment]
> when i run following command: `metaboss snapshot holders --creator mint_hash --output holders --v2`
> 
> i am constantly getting time out no matter which paid rpc i use. is there a change?

Probably Solana issues or just the number of accounts on `token-metadata` causing issues for RPCs. Use the command with a longer timeout: e.g. `-T 500`.

**Comment by nukec** [comment]
yeah i put 160 timeout seems like that did the job.
