### ISSUE TITLE
Update data-all not doing anything

### ISSUE THREAD

**Issue by danielmilner** [samuelvanderwaal/metaboss#164]
Metaboss: `v0.8.0`
Operating System: `MacOS - Intel`

When I run the following:
`metaboss update data-all --keypair [path to keypair] --data-dir [path to data dir] --log-level trace`

Nothing seems to be happening. The console prints out:
```
Updating …
Done!
```

But nothing is being updated. I have only 2 files in my `--data-dir` right now for testing.

My files are structured as:
```json
{
  "mint_account": "[mint account]",
  "nft_data": {
    "name": "My NFT #123",
    "symbol": "MNFT",
    "uri": "[url goes here]",
    "sellerFeeBasisPoints": 1000,
    "creators": [
      {
        "address": "[candy machine address]",
        "verified": true,
        "share": 0
      },
      {
        "address": "[royalty wallet address]",
        "verified": false,
        "share": 100
      }
    ]
  }
}
```

Am I doing something wrong?

**Comment by danielmilner** [comment]
I ended up just updating each piece individually instead of all at once. First the Creators, then the URIs.

**Comment by samuelvanderwaal** [comment]
The set up for `update data-all` can be a bit onerous to get right but I don't see anything obviously wrong that you're doing. I just tried this myself with three NFTs to test using v0.8.0 and it worked once the setup was correct, so not sure what was going on for you. A couple tips for next time:

* Using [this recipe](https://metaboss.rs/recipes.html) is probably the easiest way to get setup for `update data-all`.
* Metaboss logging is still not great, but I added the `solana-logger` library so you can now adjust the log level by prepending `RUST_LOG=<LEVEL>` before Metaboss commands to get both Metaboss logs and any Solana RPC logs
e.g.: 
`RUST_LOG=DEBUG metaboss update data-all`

**Comment by anvog777** [comment]
I am having a similar issue but with `metaboss update uri-all`

With the latest release I get `Done!` but some of the NFT isn't updated. 

I tried version 0.6.6. and it logged on to the console which one was ok and which one failed, so I can retry the failed ones.

**Comment by samuelvanderwaal** [comment]
> I am having a similar issue but with `metaboss update uri-all`
> 
> With the latest release I get `Done!` but some of the NFT isn't updated.
> 
> I tried version 0.6.6. and it logged on to the console which one was ok and which one failed, so I can retry the failed ones.

Did it not create a cache file with the list of errors?

**Comment by anvog777** [comment]
Nop, no cache file. It should be in the same directory where I am running metaboss?

**Comment by samuelvanderwaal** [comment]
> Nop, no cache file. It should be in the same directory where I am running metaboss?

Yeah, same directory. What version of Metaboss? `metaboss -V`

**Comment by samuelvanderwaal** [comment]
Closed due to inactivity. Re-open if this is still an issue.
