### ISSUE TITLE
Error: RPC response error -40000: Commitment not supported 

### ISSUE THREAD

**Issue by lucas122478** [samuelvanderwaal/metaboss#167]
Attempting to snapshot holders, using RPC from the index as suggested since mainnet doesn't work anymore
command used: 
metaboss snapshot holders --creator  (CM ID) --v2 -r https://rpc.theindex.io/mainnet-beta/<my api-key>

note: also tried CM creator

resulted in error in title. How to successfully get around this to take a screenshot of current holders?

**Comment by lucas122478** [comment]
I used https://solana-api.projectserum.com as an endpoint instead of theindex and was able to successfully take a snapshot.

**Comment by samuelvanderwaal** [comment]
Glad you got this working but that is not how you used the indexer feature, checkout the docs for next time: https://metaboss.rs/snapshot.html#indexed-data.
