### ISSUE TITLE
Snapshot Holders Broken?

### ISSUE THREAD

**Issue by bdcannon** [samuelvanderwaal/metaboss#168]
Has any logic around fetching holders recently changed for cmV2? 

Running `metaboss snapshot holders` seems to always return with a timeout. 

```
Error: error sending request for url (***): operation timed out
```

Switching private rpc providers does not seem to change the outcome either.

Any help would be appreciated and thank you!

**Comment by dobbinsi** [comment]
also running into this issue right now. i'm trying to fetch holders by update authority. also using a private rpc

**Comment by Lobix300** [comment]
Same issue here, I tested with 6 differents RPC, and with old/latest build from Metaboss, can't snapshot anything. 

`Error: error sending request for url (***): operation timed out`

**Comment by bdcannon** [comment]
@dobbinsi @Lobix300 I'm going to close this. I missed the option to increase timeouts. See below

`metaboss snapshot holders --creator <cndyID> --v2 --output <dir>  -T 600`

**Comment by bdcannon** [comment]
I was able to get it to return with the snapshot

**Comment by samuelvanderwaal** [comment]
> @dobbinsi @Lobix300 I'm going to close this. I missed the option to increase timeouts. See below
> 
> `metaboss snapshot holders --creator <cndyID> --v2 --output <dir> -T 600`

This is the correct answer, `getProgramAccounts` calls just take a long time these days so you have to manually set a long timeout.
