### ISSUE TITLE
Metaboss seems to fail to read Solana configs on Windows

### ISSUE THREAD

**Issue by samuelvanderwaal** [samuelvanderwaal/metaboss#17]
Look into this.

**Comment by ohaddahan** [comment]
I'm having the worst experience with Windows, regardless of metaboss, usually dos2unix helps.
Might want to employ similar encoding while reading in files in Windows.

**Comment by samuelvanderwaal** [comment]
> I'm having the worst experience with Windows, regardless of metaboss, usually dos2unix helps. Might want to employ similar encoding while reading in files in Windows.

Can you open a separate issue and elaborate on what kind of encoding issues you're having?
