### ISSUE TITLE
Install error on v0.8.3

### ISSUE THREAD

**Issue by LeonAlvarez** [samuelvanderwaal/metaboss#175]
Hi, I'm facing the following error during the installation using cargo:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/22636643/185478357-dd8bda2f-9efe-45e1-9aaa-293444b460aa.png">
```
   Compiling metaboss_lib v0.0.4
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
  --> /Users/leon/.cargo/registry/src/github.com-1ecc6299db9ec823/metaboss_lib-0.0.4/src/mint/mod.rs:67:9
   |
67 |         create_associated_token_account(&funder.pubkey(), &receiver, &mint.pubkey());
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^--------------------------------------------- an argument of type `&Pubkey` is missing
   |
note: function defined here
  --> /Users/leon/.cargo/registry/src/github.com-1ecc6299db9ec823/spl-associated-token-account-1.1.1/src/instruction.rs:91:8
   |
91 | pub fn create_associated_token_account(
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: provide the argument
   |
67 |         create_associated_token_account(&funder.pubkey(), &receiver, &mint.pubkey(), /* &Pubkey */);
   |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `metaboss_lib` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `metaboss v0.8.3`, intermediate artifacts can be found at `/var/folders/pw/6ks30h41199dr4fv0x46x7th0000gn/T/cargo-installOz4h49`
```

**Comment by Jrejoire** [comment]
Same problem for my self and a community member. 
My rust versions is the following: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by Jrejoire** [comment]
Not sure on how to fix that in the original code but here is a temporary fix.

![image](https://user-images.githubusercontent.com/33304306/185584637-9bc8d94f-93ae-4ecb-afaa-e886853d8e82.png)

- click the link to the mod.rs in the .cargo\registery folder
(Like this in my error message: `C:\Users\<USERNAME>\.cargo\registry\src\github.com-1ecc6299db9ec823\metaboss_lib-0.0.4\src\mint\mod.rs:67:9`)
- add `&TOKEN_PROGRAM_ID` as a 4th parameter in the `create_associated_token_account` function (line 67) 
- run `cargo install --path ./` again

**Comment by samuelvanderwaal** [comment]
Looks like Solana added a new parameter in `spl-associated-token-account` function and I'm not pinning to patch versions so when you run `install` without `--locked` it's grabbing the newest version of the library. 

I'll see if I can get a new version of metaboss_lib out this weekend and also update metaboss, but in the meantime the solution to this is to either install with `--locked` so it uses the existing lock file which points to the older version of `spl-associated-token-account` or just use one of the existing binaries for 0.8.3.

Install with locked:
```bash
metaboss install --path ./ --locked
```

Install binary on Linux, macOS, and WSL:
```bash
bash <(curl -sSf https://raw.githubusercontent.com/samuelvanderwaal/metaboss/main/scripts/install.sh)
```

Windows binary:
https://github.com/samuelvanderwaal/metaboss/releases/download/v0.8.3/metaboss-windows-latest.exe
