### ISSUE TITLE
Snapshot timeout

### ISSUE THREAD

**Issue by Jrejoire** [samuelvanderwaal/metaboss#176]
I have not been able to do the snapshot of holders on mainnet-beta.
It always times out. I am using a QuickNode custom RPC 

I typed the following command with the candy machine id: 
`metaboss snapshot holders --creator GGfZdPVXXXXXXXXXXXX --v2 --output ./`

Response:
`>>>>Getting accounts... (for 15 seconds)`

then:
```
Error: error sending request for url (https://fabled-spring-gas.solana-mainnet.discover.quiknode.pro/XXXXX/): operation timed out

Caused by:
    0: error sending request for url (https://fabled-spring-gas.solana-mainnet.discover.quiknode.pro/XXXXX/): operation timed out
    1: operation timed out
    
```

Solana network seems fine right now (2,361 TPS). Any ideas what could be the cause of that error?

**Comment by samuelvanderwaal** [comment]
> I have not been able to do the snapshot of holders on mainnet-beta. It always times out. I am using a QuickNode custom RPC
> 
> I typed the following command with the candy machine id: `metaboss snapshot holders --creator GGfZdPVXXXXXXXXXXXX --v2 --output ./`
> 
> Response: `>>>>Getting accounts... (for 15 seconds)`
> 
> then:
> 
> ```
> Error: error sending request for url (https://fabled-spring-gas.solana-mainnet.discover.quiknode.pro/XXXXX/): operation timed out
> 
> Caused by:
>     0: error sending request for url (https://fabled-spring-gas.solana-mainnet.discover.quiknode.pro/XXXXX/): operation timed out
>     1: operation timed out
>     
> ```
> 
> Solana network seems fine right now (2,361 TPS). Any ideas what could be the cause of that error?

Set the timeout to be longer with the `-T` option:

```
metaboss snapshot holders --creator GGfZdPVXXXXXXXXXXXX --v2 --output ./ -T 300
```
