### ISSUE TITLE
Is this a CLI only tool or can I use this from by Anchor Program?

### ISSUE THREAD

**Issue by thegitparticle** [samuelvanderwaal/metaboss#177]

**Comment by samuelvanderwaal** [comment]
It's a CLI only tool. There's a very rudimentary lib for it that has some of the functions, but they're mostly useful for client side programs, not on-chain ones. 

https://github.com/samuelvanderwaal/metaboss_lib

**Comment by thegitparticle** [comment]
@samuelvanderwaal Alright, thanks!
