### ISSUE TITLE
Add counters/status for long-running commands

### ISSUE THREAD

**Issue by samuelvanderwaal** [samuelvanderwaal/metaboss#18]
Long running commands such as snapshots should have counters or statuses to inform the user of progress, instead of just hanging.

**Comment by ohaddahan** [comment]
And an option to resume? As in, catch a break signal and dump data to format and be able to reread it and restart from the same spot?

**Comment by samuelvanderwaal** [comment]
> And an option to resume? As in, catch a break signal and dump data to format and be able to reread it and restart from the same spot?

Yeah, this would be nice. I will have to look into it but it will likely be after I do a basic counter/status.
