### ISSUE TITLE
allow to update `Uses` if it was originally null

### ISSUE THREAD

**Issue by mugveiga** [samuelvanderwaal/metaboss#181]
would be very handy to set `Uses` via metaboss since candy machine and sugar wont set it.

A simple approach to a void miss usage would be to allow it to be set if it was originally null (so you dont override already used nfts).

i think it would be on `src/update/data.rs` at line 50 or so.

**Comment by samuelvanderwaal** [comment]
@mugveiga 

What do you think of [this implementation](https://github.com/samuelvanderwaal/metaboss/pull/190)?

**Comment by mugveiga** [comment]
@samuelvanderwaal looks good! thanks :)
