### ISSUE TITLE
Error 0x37 on Creators Update command

### ISSUE THREAD

**Issue by Dictatorsnft** [samuelvanderwaal/metaboss#183]
`RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x37`
when trying to update creators, the command works with --append but has no effect on creators as I am trying to change the shares while keeping the creators same as before

**Comment by samuelvanderwaal** [comment]
You can use `metaboss find error <error_code>` to look up these annoying hex errors:

```bash
~$ metaboss find error 0x37
	Token Metadata |	CannotUnverifyAnotherCreator: You cannot unilaterally unverify another creator
Done!
```

If your NFT has a verified creator on it, the creator has to unverify themselves before you can remove them from the creators array.
