### ISSUE TITLE
Update/change creator wallet addresses?

### ISSUE THREAD

**Issue by DeeDeeDig** [samuelvanderwaal/metaboss#19]
Hello,

Thanks for the amazing tool!

Is it possible to update/change the wallet addresses associated with an NFT (collection)?

**Comment by samuelvanderwaal** [comment]
What do you mean by the "wallet addresses associated with an NFT collection"? Do you mean change the creators array?

**Comment by DeeDeeDig** [comment]
As in the wallet addresses that secondary royalties are sent as written to
the metadata.

I currently have two addresses, a primary "earnings" wallet and a "charity"
wallet that split secondary market royalties 85/15.

I need to change both of those addresses but am unsure if or how to do so.

**Comment by DeeDeeDig** [comment]
Actually, there are a handful of things that I could use a few pointers on. Would there be any way to get in touch with you directly to inquire? Happy to compensate you for your time; just don't want to tinker with anything that would cause catastrophic repercussions for current holders.

**Comment by samuelvanderwaal** [comment]
Easiest thing to do is contact me on Discord @archaeopteryx#7615 or send me an email at sam@vanderwaal.dev.
