### ISSUE TITLE
root bin metaboss line 1: Not: Command not found

### ISSUE THREAD

**Issue by mega7mega** [samuelvanderwaal/metaboss#193]
after running the installation script on windows ubuntu when i try to run metaboss. file is there.

root bin metaboss line 1: Not: Command not found
![image](https://user-images.githubusercontent.com/114383396/192207456-7cbc9843-1387-446b-a5c8-17e16be1261b.png)

i also compiled the source.. same problem

**Comment by samuelvanderwaal** [comment]
> after running the installation script on windows ubuntu when i try to run metaboss. file is there.
> 
> root bin metaboss line 1: Not: Command not found ![image](https://user-images.githubusercontent.com/114383396/192207456-7cbc9843-1387-446b-a5c8-17e16be1261b.png)
> 
> i also compiled the source.. same problem

Did you get a successful message after running the install script and did you try restarting the terminal?

**Comment by mega7mega** [comment]
yes to both. in the end i had to use the windows binary.
when using the windows binary i noticed that in parse.rs there is a function convert_local_to_remote_data
which sends an error if creators is set to null. it would be nice to have that work with creators set to null or not defined because i am changing token data not nfts.

**Comment by samuelvanderwaal** [comment]
> yes to both. in the end i had to use the windows binary. when using the windows binary i noticed that in parse.rs there is a function convert_local_to_remote_data which sends an error if creators is set to null. it would be nice to have that work with creators set to null or not defined because i am changing token data not nfts.

A [PR for that](https://github.com/samuelvanderwaal/metaboss/pull/191) was already merged into `main` and so that feature will be in the next release.
