### ISSUE TITLE
v0.9.0 Install script fails as the release name is not ubuntu-latest

### ISSUE THREAD

**Issue by 0xSuperMan** [samuelvanderwaal/metaboss#196]
While trying to install using the bash script, it tries to get the ubuntu-latest release file, but as I checked the release name is different.

metaboss-buildjet-4vcpu-ubuntu-2204
https://github.com/samuelvanderwaal/metaboss/releases/download/v0.9.0/metaboss-buildjet-4vcpu-ubuntu-2204

Also it would be super handy if the script can ask for specific version or install latest.

**Comment by samuelvanderwaal** [comment]
Good catch. I've updated the binary name in the v0.9.0 release and [updated the build action](https://github.com/samuelvanderwaal/metaboss/commit/8f346a56d610f46d5c36a675132058b420ae3f69). Will consider improving the script for versions later.

**Comment by 0xSuperMan** [comment]
> Can I create a PR with the version flag?

**Comment by samuelvanderwaal** [comment]
> Can I create a PR with the version flag?

Please do, thanks!

**Comment by 0xSuperMan** [comment]
> > Can I create a PR with the version flag?
> 
> Please do, thanks!

Done, created 2 PRs
