### ISSUE TITLE
"operation timed out" when taking a holders snapshot

### ISSUE THREAD

**Issue by oboxodo** [samuelvanderwaal/metaboss#20]
It really doesn't seem like this would be a bug on metaboss... but would you briefly list possible reasons/workarounds for this?

I'm trying to take a daily holders snapshot, but I _almost always_ get "operation timed out". I'm using an unlimited private RPC from GenesysGo which is working just fine for everything else I do, so I can't think of why it would timeout only for metaboss.

**Comment by samuelvanderwaal** [comment]
Can you post or DM the command you're running so I can try it on my end? I don't need your RPC node info just the update authority or candy machine address you're using.

**Comment by oboxodo** [comment]
Sent CM ID via Twitter DM.

**Comment by samuelvanderwaal** [comment]
> Sent CM ID via Twitter DM.

I don't see it. Did you send it to @archaeopteryx#7615? What's your Discord handle?

**Comment by oboxodo** [comment]
@samuelvanderwaal sent it via Twitter. But I'm sending it via Discord in a minute.

**Comment by samuelvanderwaal** [comment]
Twitter is fine, sorry I misread that.

**Comment by oboxodo** [comment]
@samuelvanderwaal thanks for looking into this! Now that v0.2.2 includes the `--timeout` param, I was able to fetch from my RPC. It took 4m44s :grimacing: 

Closing this.
