### ISSUE TITLE
How to update the metadata of a Metaplex Collection. 

### ISSUE THREAD

**Issue by Saviour1001** [samuelvanderwaal/metaboss#203]
Updating the entire candy machine is given in the [docs](https://metaboss.rs/update.html#update-data) but as the Data struct is different for the [Metaplex Collection](https://docs.metaplex.com/developer-tools/sugar/guides/preparing-assets#-metadata-collectionjson) as compared to the tokens,  I am running into errors. 

I am looking forward for the ways to update NFT Collection Metadata

**Comment by samuelvanderwaal** [comment]
> Updating the entire candy machine is given in the [docs](https://metaboss.rs/update.html#update-data) but as the Data struct is different for the [Metaplex Collection](https://docs.metaplex.com/developer-tools/sugar/guides/preparing-assets#-metadata-collectionjson) as compared to the tokens, I am running into errors.
> 
> I am looking forward for the ways to update NFT Collection Metadata

You need to follow the data struct listed in the Metaboss docs as that's the on-chain format. You can get that data struct by running `metaboss decode mint` with the `--full` option. Alternately, if you just need to update a single value, such as symbol or creators array, you can use the specific Metaboss command for that: `metaboss update creators-all`, `metaboss update symbol-all`.

**Comment by Saviour1001** [comment]
Solved it thanks ! 
- Ran the command ```metaboss decode mint``` with ```--full``` option. 
- Got the data struct in an output file. 
- Changed the data struct as I required it to be. 
- Tried the ```metaboss update``` command now, but it gave errors like missing field in the data structure. 
- Did the complete process without the ```--full``` option and it worked.

**Comment by samuelvanderwaal** [comment]
> Solved it thanks !
> 
> * Ran the command `metaboss decode mint` with `--full` option.
> * Got the data struct in an output file.
> * Changed the data struct as I required it to be.
> * Tried the `metaboss update` command now, but it gave errors like missing field in the data structure.
> * Did the complete process without the `--full` option and it worked.

Oh you're right. The `update` wants the partial data for just the data struct. Glad you got it to work!
