### ISSUE TITLE
metaboss will not let me update NFT's

### ISSUE THREAD

**Issue by veen2222** [samuelvanderwaal/metaboss#205]
What I want to do is an update of one of the creator's address for all of the NFT's in a collection, and all of these NFT's are already minted. I assumed the command to do this is 'metaboss update creators-all' except when I try do use this to update the NFT's I get this error response 'Error: network request failed after three attempts: ensure you used a valid address and check the state of the Solana cluster' and when I run the command with a '--log-level trace' I get this message three times before the error message, 'TRACE solana_client::nonblocking::rpc_client] Response account (address) None'. I have also tried the command with the --rpc command to ensure the RPC networks are the same, yet I still get the same error. Why is this happening? and how can I change it so that I can update the NFT's?

**Comment by samuelvanderwaal** [comment]
> What I want to do is an update of one of the creator's address for all of the NFT's in a collection, and all of these NFT's are already minted. I assumed the command to do this is 'metaboss update creators-all' except when I try do use this to update the NFT's I get this error response 'Error: network request failed after three attempts: ensure you used a valid address and check the state of the Solana cluster' and when I run the command with a '--log-level trace' I get this message three times before the error message, 'TRACE solana_client::nonblocking::rpc_client] Response account (address) None'. I have also tried the command with the --rpc command to ensure the RPC networks are the same, yet I still get the same error. Why is this happening? and how can I change it so that I can update the NFT's?

What is the full command you ran?

**Comment by veen2222** [comment]
I made some changes and the error I am getting now is "Action failed with error: RPC response error -32002: Transaction simulation failed: Blockhash not found" , it normally will say updating NFT's and show the progress bar, then once the bar is filled it says "updates failed retrying" and after that "Reached max retries. Writing remaining items to cache."

the command I am using is:

 metaboss.exe update creators-all --keypair mints.json --mint-list (path for mint list) --new-creators(new creators data) --rpc https://solana-api.projectserum.com

what could be the cause of this error why wouldn't it work?

**Comment by samuelvanderwaal** [comment]
> I made some changes and the error I am getting now is "Action failed with error: RPC response error -32002: Transaction simulation failed: Blockhash not found" , it normally will say updating NFT's and show the progress bar, then once the bar is filled it says "updates failed retrying" and after that "Reached max retries. Writing remaining items to cache."
> 
> the command I am using is:
> 
> metaboss.exe update creators-all --keypair mints.json --mint-list (path for mint list) --new-creators(new creators data) --rpc https://solana-api.projectserum.com
> 
> what could be the cause of this error why wouldn't it work?

Might be an RPC issue. Try using a different one like QuickNode, or just run the command again using the cache file `-c <cache_file>` to retry only the failed ones.
