### ISSUE TITLE
 RPC response error 

### ISSUE THREAD

**Issue by giface** [samuelvanderwaal/metaboss#206]
$ metaboss sign all --keypair  [Key Pair JSON PATH] --creator [CANDY MACHINE ID V2] --v2

Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.

Caused by:
RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.

**Comment by samuelvanderwaal** [comment]
> $ metaboss sign all --keypair [Key Pair JSON PATH] --creator [CANDY MACHINE ID V2] --v2
> 
> Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.
> 
> Caused by: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.

What version of Metaboss and what format is you keypair file?

**Comment by giface** [comment]
I'm running:
$ metaboss --version
Metaboss 0.10.0

Keypair file is in JSON Array.

**Comment by samuelvanderwaal** [comment]
> I'm running: $ metaboss --version Metaboss 0.10.0
> 
> Keypair file is in JSON Array.
> 
> Also, the same RPC error occur in snapshots function without using the keypair which I never experience before:
> 
> $ metaboss snapshot mints --creator [CANDY MACHINE ID V2] --v2 --output . Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.
> 
> Caused by: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.

What RPC provider?

**Comment by giface** [comment]
I tried both :
RPC URL: https://api.devnet.solana.com
and
Quicknode

But both return the same error.

**Comment by samuelvanderwaal** [comment]
Upgrade to Metaboss v0.10.1 and see if it fixes the issue.

**Comment by giface** [comment]
YES !! That was the problem MemcmpEncodedBytes Base58 variant was deprecated. Change from Base58 to Byte definitely helps now. Thank you again for your help. Please keep up with the great work of Metaboss.

**Comment by samuelvanderwaal** [comment]
> YES !! That was the problem MemcmpEncodedBytes Base58 variant was deprecated. Change from Base58 to Byte definitely helps now. Thank you again for your help. Please keep up with the great work of Metaboss.
> 
> Please Close this issue.

What's weird is it's not deprecated in the docs and the variant it tells you to use *is* deprecated. I've opened an issue with Solana but glad that this is working again.
