### ISSUE TITLE
RPC response error -32602

### ISSUE THREAD

**Issue by Koni20021** [samuelvanderwaal/metaboss#207]
When ever I try to run snapshot command in metaboss it gives me this error although I am on devnet rpc and my candy machine is working great I can mint from it so not a problem in candymachine. Please help!!!

metaboss snapshot mints --creator 2eYUEVNZKGgXFA3N1Fvzp8AZjJLGCCBF8HуXAHрY8f1U --v2 --output ./ Error: RPC response error -32602: Invalid params: unknown variant base58, expected `binary`.

Caused by:

RPC response error -32602: Invalid params: unknown variant `base58, expected `binary`.

**Comment by samuelvanderwaal** [comment]
I get a different error:

<img width="1106" alt="Screen Shot 2022-10-06 at 7 57 56 AM" src="https://user-images.githubusercontent.com/1684605/194361528-eabf7d56-31ae-49f2-9bb8-47b7361f1397.png">

Did you copy paste `2eYUEVNZKGgXFA3N1Fvzp8AZjJLGCCBF8HуXAHрY8f1U` correctly? Looks like it's not a valid pubkey.

**Comment by samuelvanderwaal** [comment]
For the RPC error, upgrade to Metaboss v0.10.1 and see if it fixes the issue.

**Comment by Koni20021** [comment]
Ok I'll try and get back to you ASAP please help me solve this problem I've been stuck here for like past 3 days. I'll get back to you.

**Comment by Koni20021** [comment]
it work thanks.
