### ISSUE TITLE
Metaboss update creator-all all NFTs fail to update

### ISSUE THREAD

**Issue by ZenRepublic** [samuelvanderwaal/metaboss#209]
Updating NFTs. . .
180/180 updates failed. Retrying. . .
Updating NFTs. . .
180/180 updates failed. Retrying. . .
Updating NFTs. . .
180/180 updates failed. Retrying. . .
Updating NFTs. . .
180/180 updates failed. Retrying. . .
Updating NFTs. . .
180/180 updates failed. Retrying. . .
Updating NFTs. . .
Reached max retries. Writing remaining items to cache.
Done!

PLS HELP SIR :<
tried different RPCs, seems like this one works the best: https://rpc.ankr.com/solana
but still it always fails

**Comment by samuelvanderwaal** [comment]
> Updating NFTs. . . 180/180 updates failed. Retrying. . . Updating NFTs. . . 180/180 updates failed. Retrying. . . Updating NFTs. . . 180/180 updates failed. Retrying. . . Updating NFTs. . . 180/180 updates failed. Retrying. . . Updating NFTs. . . 180/180 updates failed. Retrying. . . Updating NFTs. . . Reached max retries. Writing remaining items to cache. Done!
> 
> PLS HELP SIR :< tried different RPCs, seems like this one works the best: https://rpc.ankr.com/solana but still it always fails

Check the cache file in the same directory you ran the program to see what the errors are.

**Comment by katochayush** [comment]
same issue "error": "Action failed with error: network request failed after three attempts: ensure you used a valid address and check the state of the Solana cluster"

**Comment by bothamf** [comment]
I am having the same issue as the above ^

**Comment by samuelvanderwaal** [comment]
It's failing to decode the current data from the items in your mint list. Is your mint list correct? Maybe post a couple examples from the mint list here so I can take a look at them.

**Comment by bothamf** [comment]
thanks for getting back. Here it is. 
![Screenshot 2022-10-12 at 08 44 05](https://user-images.githubusercontent.com/111432203/195281666-31258a70-5df6-4690-a88f-04251b438785.png)

**Comment by bothamf** [comment]
Thanks for getting back. The address is correct. 
![Screenshot 2022-10-12 at 08 45 45](https://user-images.githubusercontent.com/111432203/195281877-c3258910-3c59-403c-8530-bc396c4c82f0.png)

**Comment by samuelvanderwaal** [comment]
> Thanks for getting back. The address is correct. ![Screenshot 2022-10-12 at 08 45 45](https://user-images.githubusercontent.com/111432203/195281877-c3258910-3c59-403c-8530-bc396c4c82f0.png)

I need the actual mint account so I can copy paste it and try looking at it in an explorer.

**Comment by bothamf** [comment]
77hHw476DSB5wAkGUT35o8zDy6Wj939nYvFWuyTfdns8

**Comment by samuelvanderwaal** [comment]
> 77hHw476DSB5wAkGUT35o8zDy6Wj939nYvFWuyTfdns8

This isn't a mint account: https://explorer.solana.com/address/77hHw476DSB5wAkGUT35o8zDy6Wj939nYvFWuyTfdns8. Using this address to update your NFT wont' work because it's not an address for a NFT. It's probably your update authority or treasury wallet.

**Comment by bothamf** [comment]
Right that makes sense, this is the address of the wallet that minted the NFT. 

How do I find out the mint address? Thanks again! You've been very helpful! I am a bit of a rookie at all this! SO appreciate your time!
