### ISSUE TITLE
snapshot or holders always yields empty results (windows)

### ISSUE THREAD

**Issue by NostromoUSCSS1** [samuelvanderwaal/metaboss#21]
Hi all,

Using the latest v0.2.2 binary for windows running `.\metaboss-windows-latest.exe snapshot holders -c <candy-machine-id>` always yields empty results, where as using an online tool like "gib-meta" does output the correct data.

Is there anything I might be missing in setting this up? I've just moved the binary (.exe) inside the metaplex folder as well but it makes no difference.

Thanks!

**Comment by samuelvanderwaal** [comment]
There seems to be an issue where Metaboss doesn't read the Solana config file correctly on Windows so it defaults to devnet. Try passing in your rpc url with the `--rpc` flag and see if it resolves the issue.

**Comment by NostromoUSCSS1** [comment]
.\metaboss-windows-latest.exe snapshot holders --rpc https://api.mainnet-beta.solana.com --candy-machine-id <ID>

returns

`error: Found argument '--rpc' which wasn't expected, or isn't valid in this context

USAGE:
    metaboss-windows-latest.exe snapshot holders --candy-machine-id <candy-machine-id>

For more information try --help`

**Comment by samuelvanderwaal** [comment]
Take a look at the usage section for `--rpc` in the README. You have to pass it directly to the metaboss command like this:

`metaboss -r https://api.mainnet-beta.solana.com snapshot holders -c <CANDY_MACHINE_ID>`
I recommend renaming your binary to make your life easier.

**Comment by samuelvanderwaal** [comment]
Latest version should fix the issue reading the config file so you shouldn't need to pass in the RPC if you have a valid Solana config set up: https://github.com/samuelvanderwaal/metaboss/releases/tag/v0.2.3.

**Comment by samuelvanderwaal** [comment]
@NostromoUSCSS1 did this solve your issue?
