### ISSUE TITLE
on-chain metadata doesn't get updated 

### ISSUE THREAD

**Issue by shucks18** [samuelvanderwaal/metaboss#211]
I am on V 0.8.7 of metaboss, what im trying to do is essentially update name, symbol and uri of my NFTs with **metaboss update all** 
everything goes smoothly and outputs : 
![image](https://user-images.githubusercontent.com/81901871/195773654-7b004b64-2fff-44a4-9a3e-637beaf6da75.png)

But it doesn't update the metadata on-chain

**Comment by samuelvanderwaal** [comment]
I think I saw you in the Metaboss Discord chat. Was this resolved?

**Comment by shucks18** [comment]
Hey yes it is resolved.
