### ISSUE TITLE
Metaboss update creator-all not working

### ISSUE THREAD

**Issue by abrarmusa** [samuelvanderwaal/metaboss#212]
Constantly getting this on trying to do an update creator-all

This is the code i am running:
`
metaboss update creators-all  --keypair ./keypair.json --mint-list mint_accounts.json --new-creators 4NJMQcNqz6rtBSEMJwEXRsim98rHQNuz4eL9XHvxoMGa:100:false --timeout 30
`

`444/444 updates failed. Retrying. . .
Updating NFTs. . .
Reached max retries. Writing remaining items to cache.
Done!`

This is the error in the cache file:
`  "1whYgQLxveqYyQqNFEaMgjFGZJAK6b6jRNALLXvBcEs": {
    "error": "Action failed with error: network request failed after three attempts: ensure you used a valid address and check the state of the Solana cluster"
  }`
  
  This is the wallet i am using: HNmAjdU6BbQFXjstx5dZpcfNK9ZPMG4kf62y4iC3zJSp

**Comment by samuelvanderwaal** [comment]
1. Are you on the right cluster? Mainnet vs devnet
2. Is your mint list correct?

**Comment by abrarmusa** [comment]
mainnnet
yes

**Comment by abrarmusa** [comment]
here is an example

https://solscan.io/token/1whYgQLxveqYyQqNFEaMgjFGZJAK6b6jRNALLXvBcEs

**Comment by samuelvanderwaal** [comment]
You can't unilaterally unverify the first verified creator: 

<img width="483" alt="Screen Shot 2022-10-28 at 9 54 56 AM" src="https://user-images.githubusercontent.com/1684605/198701328-dbf3c621-a590-4f93-91ae-fa89da62520d.png">

Add that as a verified creator to your new creators string.

**Comment by abrarmusa** [comment]
ahhh okay got it sir
