### ISSUE TITLE
missing field `rentEpoch`

### ISSUE THREAD

**Issue by Jrejoire** [samuelvanderwaal/metaboss#218]
Hello there,

While doing a collections migrate command I had the following error showing:
```
metaboss collections migrate -k keypair.json -c <CMV2_ID> --mint-address <COLLECTION_MINT_ADDRESS> -T 300
Using candy machine id to fetch mint list. . .
Error: missing field `rentEpoch`

Caused by:
    missing field `rentEpoch`
```
I tried re building the code and running a snapshot command instead but got the same error.
The weird thing is that I was using the same exact command in the morning and it was working. Not sure what changed.

Hope you can help.

Best regards,

**Comment by Jrejoire** [comment]
Actually this happened after changing my rpc from QuickNode to Alchemy. It's working now that I changed back.

**Comment by iofreestyle** [comment]
I'm actually experiencing the same issue and switching RPCs hasn't helped. It was previously working

**Comment by samuelvanderwaal** [comment]
> I'm actually experiencing the same issue and switching RPCs hasn't helped. It was previously working

My guess is something in a new version of Solana broke this.  I'll take a look when I get a chance.
