### ISSUE TITLE
Failing to mint NFT

### ISSUE THREAD

**Issue by acharmedmatrix** [samuelvanderwaal/metaboss#24]
Using the mint command I am receiving the following error: 

Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x26 [41 log messages]

Caused by:
RPC response error -32002: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x26 [41 log messages]

**Comment by samuelvanderwaal** [comment]
The error you're getting is:

```bash
0x26: 
	Token Metadata            |	MustBeOneOfCreators: If using a creators array, you must be one of the creators listed
```

Try adding your update_authority to the creator's array. I'm not sure why this is necessary but I've seen other people run into this issue as well.

**Comment by acharmedmatrix** [comment]
I was able to resolve by adding the keypair account as a creator with a 0 share. Thanks so much for the help!
