### ISSUE TITLE
update creators error

### ISSUE THREAD

**Issue by iSyqozz** [samuelvanderwaal/metaboss#240]
metaboss -r https://rpc.helius.xyz/?api-key=0ab43d21-ae86-48cd-ab1b-d22d667dcb6d update creators -k wallets/update_auth.json -a 8PUkZU1oaYnYLzP5nEuCMYBEVH4DZ5DiRHt3cRd3q1CX --new-creators 42NevAWA6A8m9prDvZRUYReQmhNC3NtSZQNFUppPJDRB:70:false,AVdBTNhDqYgXGaaVkqiaUJ1Yqa61hMiFFaVRtqwzs5GZ:30:false

 
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x37 [5 log messages]

what could be the issue?

**Comment by 0xraffa** [comment]
@iSyqozz The sequence of arguments is wrong. `update creators` should come before RPC. Try the following

`metaboss update creators -r https://rpc.helius.xyz/?api-key=0ab43d21-ae86-48cd-ab1b-d22d667dcb6d  -k wallets/update_auth.json -a 8PUkZU1oaYnYLzP5nEuCMYBEVH4DZ5DiRHt3cRd3q1CX --new-creators 42NevAWA6A8m9prDvZRUYReQmhNC3NtSZQNFUppPJDRB:70:false,AVdBTNhDqYgXGaaVkqiaUJ1Yqa61hMiFFaVRtqwzs5GZ:30:false`

**Comment by samuelvanderwaal** [comment]
Use metaboss to look up the error:

```bash
metaboss find error 0x37
```

```
	Token Metadata |	CannotUnverifyAnotherCreator: You cannot unilaterally unverify another creator
```

That means there's a creator in your list that current is verified `true` that you're setting to verified `false`. Only a creator can  unverify themself with their own keypair.
