### ISSUE TITLE
How to set RPC rate limit?

### ISSUE THREAD

**Issue by danielmilner** [samuelvanderwaal/metaboss#246]
I see that as of v0.5.0 you can set `custom rate limits` for RPCs. How do you do this? I've looked all over the documentation and in the CLI help, but I can't find anything about it.

**Comment by samuelvanderwaal** [comment]
Which command are you having issues with? Most of the `update` and `set` commands let you set a parallel batch size which functions sort of as a rate-limiter. I experimented with a rate-limit system previously based on specific RPCs but all the public RPCs stopped serving the kind of traffic Metaboss is commonly used for.

**Comment by danielmilner** [comment]
I am running `set token-standard-all` to fix the tokenStandard on a collection. Thinking about just writing a program to run `set token-standard` on each one individually to control the rate.

**Comment by samuelvanderwaal** [comment]
> I am running `set token-standard-all` to fix the tokenStandard on a collection. Thinking about just writing a program to run `set token-standard` on each one individually to control the rate.

Try the batch size `-b` argument with a low number like 5-10. What RPC are you running this on?

**Comment by samuelvanderwaal** [comment]
The nice part about the `*-all` methods instead of doing it singly is you get retries and a cache file with failures so you can look up the errors and run the command again using the cache file instead of having to manually prune your mint list.

**Comment by danielmilner** [comment]
It's the $10 Shakudo RPC. I'll try that, thanks!

**Comment by samuelvanderwaal** [comment]
FWIW, I use QuickNode for my Metaboss development and it works great with all the update commands so you might try them if other RPCs are giving you issues.
