### ISSUE TITLE
Unable to update token on-chain name

### ISSUE THREAD

**Issue by jnikoletich** [samuelvanderwaal/metaboss#248]
Hello,

With the latest metaboss version, after converting my collection to metaplex pNFT, it seems I can no longer update the on-chain name of NFTs:

`Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x99 [4 log messages]
root@scripts01:~/keys# metaboss find error 0x99
        Token Metadata |        InstructionNotSupported: Instruction not supported for ProgrammableNonFungible assets
Done!
`

That is the error I receive.

**Comment by samuelvanderwaal** [comment]
Updating pNFTs uses a different `update` command that hasn't been added to Metaboss yet.

**Comment by jnikoletich** [comment]
Any plans to add in the future?

**Comment by samuelvanderwaal** [comment]
> Any plans to add in the future?

You can track the status here: https://github.com/samuelvanderwaal/metaboss/pull/251

**Comment by samuelvanderwaal** [comment]
Updating pNFTs is supported now.
