### ISSUE TITLE
Update Metadata not working

### ISSUE THREAD

**Issue by wgmidiot** [samuelvanderwaal/metaboss#249]
`Error: missing field 'name' at line 36 column 1`

Haven't used this in a long time tbh, not sure if this has anything to do with Metaplex standard updates or anything.

Thanks.

<img width="1000" alt="Screenshot 2023-02-17 at 5 35 50 PM" src="https://user-images.githubusercontent.com/95952714/219809205-5f79138c-e380-4015-980a-7da5487101a1.png">

I'm running this command:

`metaboss update data --account 8G6tHU9SMqRyCaXcu9UGhYeMc51hpTcRSzYdMT97QsGg --new-data-file ./374.json`

Using the 374.json file pictured above.

_I should mention, if i put `name` at line 36, it simply moves onto output this error:_

`Error: missing field 'symbol' at line 37 column 1`

**Comment by wgmidiot** [comment]
Running Command:

`metaboss update data --account 8G6tHU9SMqRyCaXcu9UGhYeMc51hpTcRSzYdMT97QsGg --new-data-file ./374.json`

Using the 374.json file above.

**Comment by wgmidiot** [comment]
I should mention, if i put name at line 36, it simply moves onto output error for the next line of the json :


`Error: missing field symbol at line 37 column 1`

**Comment by samuelvanderwaal** [comment]
The expected data format can be found here:
https://metaboss.rs/update.html#update-data

If you only need to update a single field you might find the individual update commands easier to use, e.g.:

```bash
metaboss update name -a 8G6tHU9SMqRyCaXcu9UGhYeMc51hpTcRSzYdMT97QsGg --new-name "Ghostface #374"
```
