### ISSUE TITLE
Error when changing metadata and spl-token

### ISSUE THREAD

**Issue by HAY9885** [samuelvanderwaal/metaboss#275]
When I enter this command  `metaboss update uri -a 4VaU8pHkCmBcvycdd1tJdtzQpiP4FFsv1rMvUGZ9iUu5 -u https://gateway.pinata.cloud/ipfs/QmWVZtZMAroyEe1tWzPKrAnZBygyYMBn84RmugmoGZeZsf?_gl=1 -k HAY2.json`
I am getting this  `error Error: Action failed with error: failed to get account data`
And I checked, the token account, etc. everything is fine.
And enough money for the commission

**Comment by samuelvanderwaal** [comment]
You're trying to update the metadata on a [mint account](https://solscan.io/token/4VaU8pHkCmBcvycdd1tJdtzQpiP4FFsv1rMvUGZ9iUu5#metadata) that has no accompanying [metadata account](https://solscan.io/account/Hh4Hz1Aj9KiUfEBmBqvfnJtJ7p8eH2K9F5NYf7VLAL21).

**Comment by HAY9885** [comment]
Can you please explain how to do it
I'm just learning 😁

**Comment by samuelvanderwaal** [comment]
> Can you please explain how to do it I'm just learning 😁

I don't understand what you're trying to do. The mint account `4VaU8pHkCmBcvycdd1tJdtzQpiP4FFsv1rMvUGZ9iUu5` doesn't have any metadata associated with it so can't be updated. I think you used the wrong mint account or are confused about something. You can read more about Metaplex NFTs and tools here: https://docs.metaplex.com/.

**Comment by HAY9885** [comment]
ahh
Thank you
everything, now I understand everything
Thank you so much bro
