### ISSUE TITLE
Allow Metaboss to update Token-2022 Metadata/Accounts

### ISSUE THREAD

**Issue by mflanagan1041** [samuelvanderwaal/metaboss#287]
With the new Token-2022 program there is not a ready available way to update Token-2022 metadata easily. I think this would be beneficial since its so new and this will allow the updating of that token standard. When I try to update it now I get the following error:

 RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa

**Comment by samuelvanderwaal** [comment]
> With the new Token-2022 program there is not a ready available way to update Token-2022 metadata easily. I think this would be beneficial since its so new and this will allow the updating of that token standard. When I try to update it now I get the following error:
> 
> RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa

Token Metadata doesn't currently support token-2022 but once it does this should just work in Metaboss.
