### ISSUE TITLE
Request: Add Set Primary-Sale-Happened as an option to the mint command

### ISSUE THREAD

**Issue by znebby** [samuelvanderwaal/metaboss#29]
This will allow it to be done in the same transaction.

This covers use cases where the user has already paid for the NFT, and the mint transaction is the sale.

**Comment by samuelvanderwaal** [comment]
This makes sense and will be pretty easy to add. I'll look at doing it after I do a full release of v0.3.0.

**Comment by samuelvanderwaal** [comment]
This has been added to main and will be released in the v0.3.1 tag.
