### ISSUE TITLE
Request: ARWeave upload

### ISSUE THREAD

**Issue by znebby** [samuelvanderwaal/metaboss#30]
A simple ARWeave upload tool would be a nice to have addition to complete metaboss

**Comment by samuelvanderwaal** [comment]
I agree, and it's been on my mental to-do list for a while. It's quite a bit of work though, unfortunately, as there aren't great Arweave libraries for Rust. Caleb Everett recently wrote a Rust CLI for uploading to Arweave which you can use in the meantime and which I'll probably borrow ideas from at some point: https://github.com/CalebEverett/arloader.

**Comment by CalebEverett** [comment]
It is a pile of work to do from scratch in Rust. Good news is that I've
kind of already done it and hopefully set up the library in a way that you
could the the main functions to add commands to your cli. If you have any
questions about how it's organized, happy to help. On the other hand, the
demarcation point of arloader is links to metadata files with a nice
workflow for getting them updated with links to your assets. So you could
run arloader and then get back a nice json file of links you would use to
update your metaboss json objects. I'd also be happy to take that a step
further and add a function to output json in metaboss format if you think
that would be useful.

**Comment by CalebEverett** [comment]
These are a little sparse, but here are the docs on the lib https://docs.rs/arloader/0.1.30/arloader/

**Comment by samuelvanderwaal** [comment]
> These are a little sparse, but here are the docs on the lib https://docs.rs/arloader/0.1.30/arloader/
> 
> and of course I'd take issue with this ;)
> 
> > as there aren't great Arweave libraries for Rust

I didn't realize you had broken this out into an actual library. This is great!

**Comment by CalebEverett** [comment]
I did end up adding a command to export the `items` links that I understand the candy machine expects so may not be a bad workflow to use arloader and then take your `items` links json file and start using metaboss. But I also broke out all the commands into their own module if you wanted to include lower level functionality in your cli.

**Comment by kevinrodriguez-io** [comment]
Inspired by this I built https://github.com/kevinrodriguez-io/harbor quite a while ago for uploading into arweave. It's super flexible.

**Comment by CalebEverett** [comment]
@kevinrodriguez-io looks cool! A couple of things you might want to consider on the arweave upliad:

1. Unfortunately, you can't just rely on the presence of the file at the url as conformation that it has been successfully uploaded. Arweave aggressively caches everything, even failed transactions, so you have to check status and make sure confirmations are greater than 25.
2. You may want to consider implementing bundles to reduce the number of transactions by a couple orders of magnitude. Otherwise, you run the risk of failed tx, with for example a 10k collection, you would have 20k transactions and Arweave can only write 1000 every two minutes.

**Comment by kevinrodriguez-io** [comment]
That's great insight on the arweave uploader, I've been strongly considering moving to bundlr and requesting only a solana keypair. That would be the best. Right now arweave upload is a bit choppy but at it defends itself against empty txs (No blank nfts)
