### ISSUE TITLE
 HTTP status client error

### ISSUE THREAD

**Issue by PurpleRupeeSol** [samuelvanderwaal/metaboss#306]
Tried running the following:

metaboss snapshot mints -c n54ZwXEcLnc3o7zK48nhrLV4KTU5wWD4iq7Gvdt5tik
Error: HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)

Caused by:
    HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)
    
Any help would be massively appreciated! Thanks!

**Comment by samuelvanderwaal** [comment]
Snapshot commands don't work on public RPC nodes because it's an extremely resource-intensive command and AFAIK all the public nodes have blocked it. You can look at using a RPC provider like QuickNode or Helius to use this command.

**Comment by rektadult** [comment]
i'm getting 400 bad request when i try this with Helius.

`Error: HTTP status client error (400 Bad Request) for url (https://mainnet.helius-rpc.com/?api-key=myapikey)

Caused by:
    HTTP status client error (400 Bad Request) for url (https://mainnet.helius-rpc.com/?api-key=myapikey)`

**Comment by samuelvanderwaal** [comment]
It should still work with Quick Node, but I need to update snapshotting in general to use the DAS API that Helius and other providers support. It's on the list of things to work on.
