### ISSUE TITLE
Error: "Action failed with error: failed to get account data"

### ISSUE THREAD

**Issue by Akkolito** [samuelvanderwaal/metaboss#309]
When i try to update de data of my token i get this error message, what ca i do to solve it ?

**Comment by rererererererererererere** [comment]
+1

**Comment by 0xkyn** [comment]
I have the same problem and I am using Solana Clusters : https://docs.solana.com/clusters
Devnet : https://api.devnet.solana.com

**Comment by samuelvanderwaal** [comment]
> I have the same problem and I am using Solana Clusters : https://docs.solana.com/clusters Devnet : https://api.devnet.solana.com
> 
> The command I am using : `metaboss update uri`

What is the mint address?

**Comment by FigrHed** [comment]
Also getting the same error on my laptop after "Metaboss update uri".
The same command worked fine on my desktop.
