### ISSUE TITLE
Using hardware wallet

### ISSUE THREAD

**Issue by 0x62** [samuelvanderwaal/metaboss#31]
I'm trying to sign the metadata for an unverified creator using a hardware wallet, but it doesn't seem to accept `usb://ledger` as a keypair. Is this possible?

**Comment by samuelvanderwaal** [comment]
Signing with a hardware wallet isn't currently supported. Hardware wallets like Ledger don't expose your private key they sign a transactions and return the signed message. This would make for a very poor user experience when signing more than a couple of transactions. Trying to do `sign_all` for 1000 NFTs, for example, would require the user to manually push the sign buttons on the Ledger 1000 times. I don't believe Ledger has a `sign_all` function in their API but will have to look at some point.
