### ISSUE TITLE
Documentation: Wrong flag used

### ISSUE THREAD

**Issue by BR1PERCENTERS** [samuelvanderwaal/metaboss#316]
https://metaboss.rs/update.html#update-creators

Wrong

`metaboss update creators -k ~/.config/solana/devnet.json -a 4rxTT8pKeYFrFgNBgTspBWVEnMnsAZGwChkjRUtP4Xpi -c 42NevAWA6A8m9prDvZRUYReQmhNC3NtSZQNFUppPJDRB:70:false,AVdBTNhDqYgXGaaVkqiaUJ1Yqa61hMiFFaVRtqwzs5GZ:30:false`

Correct

`metaboss update creators -k ~/.config/solana/devnet.json -a 4rxTT8pKeYFrFgNBgTspBWVEnMnsAZGwChkjRUtP4Xpi -n 42NevAWA6A8m9prDvZRUYReQmhNC3NtSZQNFUppPJDRB:70:false,AVdBTNhDqYgXGaaVkqiaUJ1Yqa61hMiFFaVRtqwzs5GZ:30:false`

=> Flag should be `-n`, not `-c`

**Comment by samuelvanderwaal** [comment]
Thanks, fixed.
