### ISSUE TITLE
Not runig on Ubuntu 23.10

### ISSUE THREAD

**Issue by theCoinCreator** [samuelvanderwaal/metaboss#319]
when trying to run the metaboss tool I get this Error "metaboss: error while loading shared libraries: libssl.so.1.1".

This seams to have to do with the fact the libery libssl.so is on version 3 starting on version 22. So i guess you would need to update your Files/Project to use the new version?

Thank you

**Comment by samuelvanderwaal** [comment]
> when trying to run the metaboss tool I get this Error "metaboss: error while loading shared libraries: libssl.so.1.1".
> 
> This seams to have to do with the fact the libery libssl.so is on version 3 starting on version 22. So i guess you would need to update your Files/Project to use the new version?
> 
> Thank you

What version of SSL is installed on your machine? Is this Ubuntu or WSL?

Run `openssl version` and post the output.

**Comment by theCoinCreator** [comment]
I am running Ubuntu 23.10 in VirtuallBox on Windows 10. Running `openssl version` returns: 
`OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)`

**Comment by samuelvanderwaal** [comment]
> > > when trying to run the metaboss tool I get this Error "metaboss: error while loading shared libraries: libssl.so.1.1".
> > > This seams to have to do with the fact the libery libssl.so is on version 3 starting on version 22. So i guess you would need to update your Files/Project to use the new version?
> > > Thank you
> > 
> > 
> > What version of SSL is installed on your machine? Is this Ubuntu or WSL?
> > Run `openssl version` and post the output.
> 
> I am running Ubuntu 23.10 in VirtuallBox on Windows 10. Running `openssl version` returns: `OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)`

This is strange. My Linux machine is also on OpenSSL 3 and does not have an issue installing Metaboss. This may be something specific to WSL and I don't have a way to test that right now. If you go to the Metaboss Discord you might find some other folks who have had the same issue and have a work around.

**Comment by samuelvanderwaal** [comment]
> when trying to run the metaboss tool I get this Error "metaboss: error while loading shared libraries: libssl.so.1.1".
> 
> This seams to have to do with the fact the libery libssl.so is on version 3 starting on version 22. So i guess you would need to update your Files/Project to use the new version?
> 
> Thank you

Another thought: are you trying to run an old version? Run `metaboss -V` to see the current installed version. The latest release is v0.36.0, so you might try updating to see if that fixes the issue.

**Comment by theCoinCreator** [comment]
Thank you for your help. I tired using the most recent version. I found another way to do what i wanted to do. So no need for me to use this tool anymore.
