### ISSUE TITLE
Getting error while updating metadata of NFT

### ISSUE THREAD

**Issue by dhavalsoni2001** [samuelvanderwaal/metaboss#324]
I have been using Metaboss to update the metadata of several NFTs. While the process has been successful for most of the NFTs, I have encountered errors with certain ones. The error message reads: 

'Error: Action failed with error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x9e [5 log messages]'

I am unsure of what this error means or how to resolve it.

**Comment by samuelvanderwaal** [comment]
> I have been using Metaboss to update the metadata of several NFTs. While the process has been successful for most of the NFTs, I have encountered errors with certain ones. The error message reads:
> 
> 'Error: Action failed with error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x9e [5 log messages]'
> 
> I am unsure of what this error means or how to resolve it.

You can look up errors with Metaboss by the error code:

```
metaboss find error 0x9e
```

in this case the error is `InvalidAuthorityType: Invalid authority type`.

**Comment by dhavalsoni2001** [comment]
Thanks for the response I will check out on our end

**Comment by dhavalsoni2001** [comment]
It's working fine, there were some issue with authority which has given to me.
