### ISSUE TITLE
Not able to update certain NFTs

### ISSUE THREAD

**Issue by dhavalsoni2001** [samuelvanderwaal/metaboss#325]
I am trying to update an NFT which is not getting updated even though I am getting a response of Tx Sign.

So basically I am trying to update following NFT:
https://magiceden.io/item-details/29FdNoir6uakN8hvMiwurHmKo7Uz1KNiugG4qLnu2bkW?name=The-Nonns-%232365

I am getting responses like this:
Tx sig: 1111111111111111111111111111111111111111111111111111111111111111

But still, it's not updated on Magiceden.

**Comment by samuelvanderwaal** [comment]
> I am trying to update an NFT which is not getting updated even though I am getting a response of Tx Sign.
> 
> So basically I am trying to update following NFT: https://magiceden.io/item-details/29FdNoir6uakN8hvMiwurHmKo7Uz1KNiugG4qLnu2bkW?name=The-Nonns-%232365
> 
> I am getting responses like this: Tx sig: 1111111111111111111111111111111111111111111111111111111111111111
> 
> But still, it's not updated on Magiceden.

You can check if it was successfully updated on-chain but looking at it in an explorer: https://solscan.io/token/29FdNoir6uakN8hvMiwurHmKo7Uz1KNiugG4qLnu2bkW#metadata. If it's successfully updated on-chain it might just take a bit for Magic Eden's cache to update.
