### ISSUE TITLE
While Updating URI getting error 

### ISSUE THREAD

**Issue by lalitp1998** [samuelvanderwaal/metaboss#326]
I am encountering an error when using the `metaboss update uri` command. The exact error message is: `Error: Action failed with error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds`.

**Comment by samuelvanderwaal** [comment]
> I am encountering an error when using the `metaboss update uri` command. The exact error message is: `Error: Action failed with error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds`.

Check to see if the URI was actually updated on-chain, sometimes the RPC simply isn't able to confirm if the transaction went through even though it may have.

**Comment by lalitp1998** [comment]
We had a conversation with chainstack team, and they said that It seems that the error is from the metaboss itself, as it does not look like an RPC error. Please contact the developers to clarify the source of such errors.
If they recommend contacting your RPC provider, please come back to us with your Node ID ND-XXX-XXX-XXX and a timestamp of the error for us to investigate further.

**Comment by samuelvanderwaal** [comment]
> We had a conversation with chainstack team, and they said that It seems that the error is from the metaboss itself, as it does not look like an RPC error. Please contact the developers to clarify the source of such errors. If they recommend contacting your RPC provider, please come back to us with your Node ID ND-XXX-XXX-XXX and a timestamp of the error for us to investigate further.

That error is just printing what the RPC returns. Did you actually check in an explorer to see if it's updated on-chain? If you check and it failed to update, then just try running the command again. Sometimes it's hard to land transactions on Solana the first time.
