### ISSUE TITLE
Issue: RPC response error -32002

### ISSUE THREAD

**Issue by kobyle69** [samuelvanderwaal/metaboss#34]
Hello,

1- Trying to do a 'metaboss update data'

> [2021-12-05T12:44:00Z DEBUG reqwest::connect] starting new connection: https://api.mainnet-beta.solana.com/
> [2021-12-05T12:44:01Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.mainnet-beta.solana.com/
> [2021-12-05T12:44:01Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.mainnet-beta.solana.com/
> [2021-12-05T12:44:01Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.mainnet-beta.solana.com/
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   2: Program log: Instruction: Update Metadata Accounts
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   3: Program log: libstd rust_begin_panic
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   4: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:773:9
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   5: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 200000 of 200000 compute units
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   6: Program failed to complete: BPF program panicked
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]   7: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
> [2021-12-05T12:44:01Z DEBUG solana_client::rpc_client]

**Comment by samuelvanderwaal** [comment]
Can you tell me what version of Metaboss you have using `metaboss -V`, and also post the full command you ran?

**Comment by kobyle69** [comment]
Version: **Metaboss 0.3.0**

Below is the command (change the wallet address), also tried several json examples, including yours in the example:

`metaboss -l trace update data --keypair /home/ubuntu/.config/solana/mainnet.json --account e3mzFDfPGE9ZC4k2bR94hVJiDbk8mK8aoRDWTmBhqMmwA --new-data-file /home/ubuntu/work/metaboss/fix/0.json`

**Comment by samuelvanderwaal** [comment]
What you're doing should work as long as the json file is the correct format. (If it's not though, you would be getting a different error directly from Metaboss.) This looks like an on-chain program error. I'm going to try to duplicate on mainnet now. The command is working fine for me on devnet.

**Comment by kobyle69** [comment]
Ok thank you, I suspected the json and tried all sort of examples and none worked, always the same error.

Thanks for the help.

**Comment by samuelvanderwaal** [comment]
I am unable to duplicate this on mainnet so far. Are you willing to DM me on Discord and provide more details there so I can troubleshoot? (Mint account, json file will be helpful for me to try to figure out the issue.)

**Comment by kobyle69** [comment]
Hey Samuel,

What is your discord handle?

Best
Koby

**Comment by samuelvanderwaal** [comment]
@archaeopteryx#7615

**Comment by kobyle69** [comment]
DM sent

**Comment by samuelvanderwaal** [comment]
For anyone who comes across this issue: the problem is passing the wrong account with the `-a` option. This should be the NFT mint/token account, not update authority, candy machine etc.. I'll look to see if there's an easy way to check this in Metaboss without requiring another RPC call.

**Comment by jclmnop** [comment]
> For anyone who comes across this issue: the problem is passing the wrong account with the `-a` option. This should be the NFT mint/token account, not update authority, candy machine etc.. I'll look to see if there's an easy way to check this in Metaboss without requiring another RPC call.

I'm getting this problem, but I'm passing the correct account(s).

**Comment by samuelvanderwaal** [comment]
> > For anyone who comes across this issue: the problem is passing the wrong account with the `-a` option. This should be the NFT mint/token account, not update authority, candy machine etc.. I'll look to see if there's an easy way to check this in Metaboss without requiring another RPC call.
> 
> I'm getting this problem, but I'm passing the correct account(s).

What is the full command you ran?

**Comment by jclmnop** [comment]
> > > For anyone who comes across this issue: the problem is passing the wrong account with the `-a` option. This should be the NFT mint/token account, not update authority, candy machine etc.. I'll look to see if there's an easy way to check this in Metaboss without requiring another RPC call.
> > 
> > 
> > I'm getting this problem, but I'm passing the correct account(s).
> 
> What is the full command you ran?

It's cool I think I solved it. 

Basically, I wrote a python script that runs metaboss commands to check whether or not a mint account has been updated, and to then update it if it hasn't. But it seems that initially my script wasn't always checking them reliably, so sometimes it was trying to update ones that have already been updated and apparently this causes the above error also.
