### ISSUE TITLE
snapshot candy machine mint accounts in correct order of mint

### ISSUE THREAD

**Issue by mistermann87** [samuelvanderwaal/metaboss#35]
Hey there,

the snapshot feature is a cool one. But is it possible to retrieve the mint accounts in the order that they were minted (ordered by date)?
That would be very helpful when someone wants to implement features based just on the NFT #id of the collection.

Thanks for your help and the great tool!

**Comment by samuelvanderwaal** [comment]
Yeah, that should be possible. I'll look into it at some point.

**Comment by samuelvanderwaal** [comment]
I don't know a great way to do this right now but it might be possible if I improve my transaction crawling library. Closing for now.
