### ISSUE TITLE
How do you change a mutable NFT to immutable?

### ISSUE THREAD

**Issue by znebby** [samuelvanderwaal/metaboss#36]
I assume update_authority should be able to do it?

**Comment by samuelvanderwaal** [comment]
This is not possible currently due to an oversight in the on-chain token-metadata program. I have an open PR that fixes it which I hope to get merged soon.

**Comment by samuelvanderwaal** [comment]
If you're curious you can track the status of the PR here: https://github.com/metaplex-foundation/metaplex-program-library/pull/25.
