### ISSUE TITLE
Mint list error 0x2d

### ISSUE THREAD

**Issue by tina1998612** [samuelvanderwaal/metaboss#37]
I tried to execute the batch mint command but encountered the following error:
```
Failed to mint "new_nfts/01.json": RPC response error -32002: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x2d [41 log messages
```

May I ask where I can find the error message and how to resolve this? Thanks!! ><

**Comment by samuelvanderwaal** [comment]
The Anchor error codes are definitely opaque and I plan to add the ability to parse them with Metaboss at some point. The code you ran into is:

```bash
0x2D:
	Token Metadata            |	ShareTotalMustBe100: Share total must equal 100 for creator array
```

which means that the total shares of all your creators have to add up to 100%. 

Until I add them to Metaboss you can use this tool to parse most of the Anchor codes: https://github.com/samuelvanderwaal/wtf-is
