### ISSUE TITLE
Metaboss not defaulting to cluster

### ISSUE THREAD

**Issue by triviatroy** [samuelvanderwaal/metaboss#38]
![image](https://user-images.githubusercontent.com/75331477/145627221-856eaad5-0b52-4676-8e24-02a830abb775.png)

**Metaboss version**: 0.3.1

**Error Message**: [2021-12-10T18:54:31Z ERROR metaboss] Could not find a valid Solana-CLI config file. Please specify a RPC manually with '-r' or set up your Solana-CLI config file.

**Command**: metaboss snapshot mints -c 5sBU6EEvBJjMKs3qpLSVhRuYcTbWYhsswnnNTYZq9zwk

**Comment by triviatroy** [comment]
Also tried: 

`metaboss -r https://api.mainnet-beta.solana.com snapshot mints -c 5sBU6EEvBJjMKs3qpLSVhRuYcTbWYhsswnnNTYZq9zwk`

Result: same error message as above comment

**Comment by samuelvanderwaal** [comment]
Thanks for the bug report. Please use v0.3.0 as that's the latest release, or set up your Solana config file to get around this issue for now.

**Comment by triviatroy** [comment]
Same error :(

**Comment by triviatroy** [comment]
Tried on both ubuntu and windows

**Comment by samuelvanderwaal** [comment]
> Same error :(

You set up your config with `solana config set --url <RPC_URL>`?

**Comment by triviatroy** [comment]
`Config File: /root/.config/solana/cli/config.yml
RPC URL: https://api.mainnet-beta.solana.com 
WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed)
Keypair Path: /root/.config/solana/id.json 
Commitment: confirmed `

Yeah understood. Its setup as the default though which I would've assumed should work.

**Comment by samuelvanderwaal** [comment]
> `Config File: /root/.config/solana/cli/config.yml RPC URL: https://api.mainnet-beta.solana.com WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed) Keypair Path: /root/.config/solana/id.json Commitment: confirmed `
> 
> Yeah understood. Its setup as the default though which I would've assumed should work.

The normal place for the config file is the user's home directory so that's where Metaboss looks for it. Any particular reason you have the config file in your root directory?

Regardless, I'll try to fix this bug tonight because it should at least accept the RPC URL you pass in via the `-r` option.

**Comment by triviatroy** [comment]
I installed the solana cli according to: https://docs.solana.com/cli/install-solana-cli-tools and it put it in the root directory

**Comment by samuelvanderwaal** [comment]
Their example shows installing it to a user account:

```
Configuration: /home/solana/.config/solana/install/config.yml
```

You were probably root user when you ran the install command, which isn't recommended. The quick fix for you would be to move the config file to: `/home/<USER>/.config/solana/cli/config.yml`

**Comment by triviatroy** [comment]
![image](https://user-images.githubusercontent.com/75331477/145640102-22e630bf-82d5-4c3a-8c07-87bda5bbd925.png)

Same thing on Windows without the config in root.

**Comment by samuelvanderwaal** [comment]
Put your config here on Ubuntu: `/home/<USER>/.config/solana/cli/config.yml`. I don't know what's going on with Windows.

**Comment by triviatroy** [comment]
Hmm... the file on my Ubuntu server doesn't actually exist and I can't find documentation and creating a new one.

**Comment by samuelvanderwaal** [comment]
> Hmm... the file on my Ubuntu server doesn't actually exist and I can't find documentation and creating a new one.

It's just a yml file, you can manually create it but I thought that running `solana config set` would create it if it doesn't exist.

**Comment by samuelvanderwaal** [comment]
@triviatroy are you still experiencing this bug?

**Comment by triviatroy** [comment]
Yeah. I haven't seen any new releases so not sure what new behavior we'd expect. solana config set doesn't create a default one either. Weird. Just trying to run on my windows machine and a ubuntu droplet. No luck either way.

**Comment by samuelvanderwaal** [comment]
> Yeah. I haven't seen any new releases so not sure what new behavior we'd expect. solana config set doesn't create a default one either. Weird. Just trying to run on my windows machine and a ubuntu droplet. No luck either way.

I fixed the RPC flow bug in v0.3.1. If it can't find your config file it should let you pass in a RPC URL directly. Let me know if that doesn't work for you for some reason.

**Comment by triviatroy** [comment]
v0.3.1 RPC option works! Much appreciated. 

Is there a more appropriate forum to ask clarifying questions? I'd like to describe what i'm trying to do and see if you have a recommendation.

**Comment by samuelvanderwaal** [comment]
> v0.3.1 RPC option works! Much appreciated.
> 
> Is there a more appropriate forum to ask clarifying questions? I'd like to describe what i'm trying to do and see if you have a recommendation.

If it's not directly Metaboss related Discord or Twitter are better options. If it's technical I prefer Discord as it has been reply options and code formatting. I can't guarantee I can support but I do try to help people who message me. There are also Solana and Metaplex specific Discords where you can get general help:

https://discord.gg/solana
https://discord.gg/PM3FZjf8
