### ISSUE TITLE
Where to see transaction error logs

### ISSUE THREAD

**Issue by kafinsalim** [samuelvanderwaal/metaboss#43]
Im executing metaboss update data and expect to be able to update metadata of an nft with a new arweave uri. it say transaction error and there are some logs. but i have no idea where to see the log. Any idea where i can see the logs?

![Screenshot 2021-12-18 at 11 42 21](https://user-images.githubusercontent.com/33047308/146629255-bb481173-8017-4640-b701-298f3a03910c.png)

**Comment by samuelvanderwaal** [comment]
The `[7 log messages]` are referring to the complete Solana transaction log messages which Metaboss isn't currently outputting. Right now all logging from Metaboss goes directly to stdout and stderr. 

The mostly cause of your issues is a malformed metadata file (make sure to follow the format specified in the docs), or issues using the public RPC.
