### ISSUE TITLE
Could not find a valid Solana-CLI config file. Please specify a RPC manually with '-r' or set up your Solana-CLI config file.

### ISSUE THREAD

**Issue by ramenation** [samuelvanderwaal/metaboss#45]
Getting these errors while trying to run metaboss on a Mac.

`metaboss decode mint -a 23gaZq8578xHozMWADsmZ2hAFqZ15iyHmQtRw14meds2
[2021-12-22T10:09:24Z ERROR metaboss] Could not find a valid Solana-CLI config file. Please specify a RPC manually with '-r' or set up your Solana-CLI config file.
`

So I try manually specifying the rpc but I get this:

`metaboss decode mint -a 23gaZq8578xHozMWADsmZ2hAFqZ15iyHmQtRw14meds2
[2021-12-22T10:09:24Z ERROR metaboss] Could not find a valid Solana-CLI config file. Please specify a RPC manually with '-r' or set up your Solana-CLI config file.
Paolos-MacBook-Pro:metaboss pao$ metaboss decode mint -r https://api.mainnet-beta.solana.com -a 23gaZq8578xHozMWADsmZ2hAFqZ15iyHmQtRw14meds2
error: Found argument '-r' which wasn't expected, or isn't valid in this context`

Solana is setup on my machine, and `solana get config` seems to be ok, so I'm not sure what the issue could be.

`Metaboss 0.3.2`

**Comment by samuelvanderwaal** [comment]
To specify a RPC pass it directly to `metaboss` command like this:

`metaboss -r <rpc_url> decode mint -a`

However, if you have a Solana config set up it should be finding that. Where is your config file located?

**Comment by ramenation** [comment]
moving the -r command right after the metaboss command worked, thanks!

config is in the default place, e.g.:
~/.config/solana/cli/config.yml

**Comment by samuelvanderwaal** [comment]
The config option works as expected on my Mac with a valid config file at `~/.config/solana/cli.config.yml`. Not sure how to troubleshoot this since I can't duplicate it. If you want an example config file to try, let me know.
