### ISSUE TITLE
Request: Add burn token

### ISSUE THREAD

**Issue by znebby** [samuelvanderwaal/metaboss#46]
Would be nice to have a command that will burn the spl token, clean up the Metadata/Master record accounts etc.

**Comment by samuelvanderwaal** [comment]
There's currently no way to close down Metadata and Edition accounts, but I could create a command that:

1) burns the SPL token
2) closes the associated token account
3) if the caller is the update authority, sets metadata to default/null values

**Comment by znebby** [comment]
Sounds useful to me

**Comment by samuelvanderwaal** [comment]
Cool, I'll see if I can add it to the next major update. I'm working on refactoring the core into a separate library and need to decide at what point I stop adding features and just get that done. Is this a feature you regularly require or something that would be useful every now again?

**Comment by znebby** [comment]
To be honest, this was simple enough that I figured out how to do it without needing Metaboss to implement it. So as far as I'm concerned, no urgent need.

**Comment by samuelvanderwaal** [comment]
#51 adds support for burning NFTs
