### ISSUE TITLE
Request: Allow setting the recentBlockhash in the all Metaboss transaction

### ISSUE THREAD

**Issue by znebby** [samuelvanderwaal/metaboss#47]
Sometimes you need to do a mint or other metaplex action in response to another transaction on the chain. However, often you want to do it before the transaction you are responding to is finalized in the cluster.

Therefore, being able to set the recent blockhash that the transaction you're pushing references, allows it to be forked out in the case that the transaction you're responding to never gets finalized / gets forked out.

**Comment by samuelvanderwaal** [comment]
Interesting use-case. Any idea what you think this API should look like?

**Comment by znebby** [comment]
I would just add --recent-blockhash

**Comment by samuelvanderwaal** [comment]
@znebby I'm going through old issues and realizing I never did this. I doubt it's still relevant to you, but if you or anyone else thinks this is still useful I can probably implement it. Otherwise I'll just close the issue.
