### ISSUE TITLE
Error: invalid variant

### ISSUE THREAD

**Issue by TEGDV** [samuelvanderwaal/metaboss#48]
I trying to run `metaboss snapshot holders -c 6pzuJN2DpgKQfVVAmVHJpaeQYYDevyBAC2jPxrYv9n3` inside a docker container but it return me `ERROR: invalid variant` some tip to figure out what its happening?

**Comment by samuelvanderwaal** [comment]
Candy machine version 1 or 2?

**Comment by samuelvanderwaal** [comment]
In our Discord chat you said you narrowed this down to being caused by running a Docker on AWS, right? Any further update on this?

**Comment by TEGDV** [comment]
Yes, Actually is the Amazon EC2 instance that fails we are using a T2.medium instance with 32 GB storage and 4GB of RAM.I managed to install metaboss on the host but after run the command `metaboss snapshot holders -c 6pzuJN2DpgKQfVVAmVHJpaeQYYDevyBAC2jPxrYv9n3` throws the same error `Error: invalid variant`
