### ISSUE TITLE
Issue: RPC response error -32002

### ISSUE THREAD

**Issue by mdstevens044** [samuelvanderwaal/metaboss#52]
I am getting the following error RPC response error -32002. I have looked previous issues and seen there was a problem with people using the wrong account but I believe I am using the right one. From the Solscan view I am using the token address. Is this the right one?

**Comment by samuelvanderwaal** [comment]
What command are you running and can you post the full error here?

**Comment by mdstevens044** [comment]
Sure thing, I am running update uri and getting the following
`Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x7 [5 log messages]

Caused by:
    RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x7 [5 log messages]`

**Comment by samuelvanderwaal** [comment]
You're using the wrong update authority: 

```bash
0x7: 
	Token Metadata            |	UpdateAuthorityIncorrect: Update Authority given does not match
```

**Comment by mdstevens044** [comment]
So I need to be running these commands from the update authority account?

**Comment by samuelvanderwaal** [comment]
> So I need to be running these commands from the update authority account?

You can only update the metadata of a NFT if 1) the is_mutable flag is set to `true` and 2) if you're the update authority, so you need to use that keypair when you run metaboss `update` or `set` commands.

**Comment by mdstevens044** [comment]
Ok thank you

**Comment by CaudalCryptoPR** [comment]
hi, im also this error when trying spl-token create token

RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0 [3 log messages]  

i dont know if its my keypair path or config file or my default signer  is lost or not set up. appreciate the help anyone.
