### ISSUE TITLE
Improve error message for "RPC response error -32002"

### ISSUE THREAD

**Issue by epomatti** [samuelvanderwaal/metaboss#54]
While I was trying to mint an NFT I was getting the bellow error on `devnet`.

The problem was my `creator.address` value was not the same address as the Solana keypair (I forgot to change it in the JSON file).

I would suggest adding a custom message so that it display the root cause early.

```json
{
    "name": "my nft",
    "symbol": "MYNFT",
    "uri": "https://arweave.net/JiHStIaDf5lSniBmBpPGKPKPFpJdXMelCslgfEPRLbE",
    "seller_fee_basis_points": 100,
    "creators": [
        {
            "address": "<I GOT THIS ADDRESS WRONG>", <--this was wrong
            "verified": false,
            "share": 100
        }
    ]
}
```

Generic error message:

```
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x26 [41 log messages]
```

Commands that I was running:

```bash
# without rpc
metaboss mint one -k $keypair --nft-data-file $nft_data_file --receiver $receiver
# with rpc
metaboss -r $rpc mint one -k $keypair --nft-data-file $nft_data_file --receiver $receiver
```

**Comment by samuelvanderwaal** [comment]
I definitely need to improve error messages for RPC response errors in general.

**Comment by Arinerron** [comment]
why was this closed? I'm having the same vague error and just found this

**Comment by samuelvanderwaal** [comment]
> why was this closed? I'm having the same vague error and just found this

I didn't close it, original opener did. He is free to re-open the issue or you can create a new one for the same problem. I will improve error messages for Metaboss when I have time to do so.

**Comment by tonyhoangtran92** [comment]
So at the end, how to improve this error? I got the same problem

**Comment by samuelvanderwaal** [comment]
> So at the end, how to improve this error? I got the same problem

You can use this tool to look up error messages. https://github.com/samuelvanderwaal/wtf-is
I want to write a proper parser for Metaboss but it's been lower priority than adding new features so far.
