### ISSUE TITLE
Images not loading after Mint on devnet

### ISSUE THREAD

**Issue by epomatti** [samuelvanderwaal/metaboss#55]
I've minted two NFTs on `devnet` but their images are not showing on the Phantom wallet.

![image](https://user-images.githubusercontent.com/6530769/148230392-35693e4c-8154-4167-b07f-690a4287e265.png)

This is the link to the armory: https://www.nftarmory.me/view/address/62BjRAuHuSUQLU4rrHFAGPbDx5as6amnZ6hkSpSTBoRW

I've tried the `creators[0].verified` field with both "true" and "false", but no success:

```json
{
    "name": "my nft",
    "symbol": "MYNFT",
    "uri": "https://arweave.net/JiHStIaDf5lSniBmBpPGKPKPFpJdXMelCslgfEPRLbE",
    "seller_fee_basis_points": 100,
    "creators": [
        {
            "address": "GBphEVmasEBHxzaotYF7PxSgZfHTCFXNRXfzySk6cKrW",
            "verified": true,
            "share": 100
        }
    ]
}
```

The code I've used to mint the NFT:

```bash
export keypair="$HOME/.config/solana/devnet.json"
export rpc='... hidden for security ...'
export receiver='62BjRAuHuSUQLU4rrHFAGPbDx5as6amnZ6hkSpSTBoRW'
export nft_data_file='/tmp/new_nft.json'

metaboss -r $rpc mint one -k $keypair --nft-data-file $nft_data_file --receiver $receiver
```

Outputs:
```
Tx id: 2oisYBcg2MtfCoKJM4LwNPNxFd4c9nxA4FMrY3Zpvzrbkw65TALUfcmSCdD1iF571gp6TrRLm4X2kg1ZNQSoohBr
Mint account: 8KGaxFov5WxrDb9a1pre46qPSwNv4aZpNcRuppRHmWMk
Done!

Tx id: 32TKgpVZTA332vAFw6weUbPTjbT5tixYaJX1qJ6p5jEBeXFTkQt1kJfiP1q5JfrsBJfxePVuUknmLyzE1v1ov5Jo
Mint account: gdUzbYNYzupdv7XoTJ18hcm7hRwBein1dggCDHAuo6z
Done!
```

Metaboss version:

```bash
$ metaboss --version
Metaboss 0.3.4
```

**Comment by samuelvanderwaal** [comment]
Thanks for the descriptive issue report it made it easy to see what the issue was. 

Metaboss doesn't check that your URI resolves to a proper JSON metadata file (maybe it should). In your case you tried to use the URI of the image directly which doesn't follow the [Metaplex Token Metdata Standard ](https://docs.metaplex.com/nft-standard). You need the URI to point to a JSON file that itself contains an image in the `image` field. See the the linked Metaplex docs.

**Comment by epomatti** [comment]
@samuelvanderwaal I got it working now with `--external-metadata-uri`.

So `--nft-data-file` is not the actual metadata, correct?

It got me confused because there are duplicate properties such as the "creators" and "seller_fee_basis_points", which will also be present in the metadata file. So I don't understand exactly why.

---
Dropping the commands here in case someone need it.

```bash
# nft_json must follow Metaplex metadata standard
arweave deploy $nft_json --key-file $arweave_key

# use the output link from the previous command
metaboss -r $rpc mint one -k $keypair -u 'https://arweave.net/WfGUujfz6cLZwaEhkHoMocXBYmvDPf1nex02xNvMxoQ' -r $receiver
```

**Comment by samuelvanderwaal** [comment]
@epomatti The `--nft-data-file` is a JSON file representing the [on-chain (Solana) metadata](https://github.com/metaplex-foundation/metaplex-program-library/blob/75a76f368351f9252e75587866ebfb4d5cdc7136/token-metadata/program/src/state.rs#L71) not the "off-chain" (Arweave, AWS, IPFS, whatever) external metadata defined by the Metaplex Token Metadata Standard. 

Metaboss lets you mint from the nft-data-json file representing the Solana `Data` struct *or* from a URI following the Metaplex Token Metadata Standard as it can get all the necessary values from that.

**Comment by epomatti** [comment]
Got it, I was not aware of that concept.
