### ISSUE TITLE
RPC response error -32002: Transaction simulation failed: Blockhash not found

### ISSUE THREAD

**Issue by shoevan** [samuelvanderwaal/metaboss#56]
When updating an NFT's on chain data am getting this the error from the title, Have also tried another NFT token address and getting a separate error:

Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x7 [5 log messages]

Command used:
metaboss -r <custom rpc url> update data --account <token Address> --keypair <location of authority keypair> --new-data-file <location of datafile>

**Comment by samuelvanderwaal** [comment]
You're using the wrong update authority keypair:

```bash
0x7: 
	Token Metadata            |	UpdateAuthorityIncorrect: Update Authority given does not match
```

**Comment by shoevan** [comment]
I've got it programmatically choosing the right authority keypair for a particular NFT, with that said I ran the exact same command again about 10mins ago and they've all updated fine, so I'm not sure what to make of it. Ticket can be closed.

**Comment by samuelvanderwaal** [comment]
Blockhash not found likely means there was a temporary error with Solana getting the blockhash (which is required to build a tx). I can probably add retries to that though I haven't seen many reported issues of this.

**Comment by jclmnop** [comment]
> I can probably add retries to that though I haven't seen many reported issues of this.

I've been getting it fairly often when minting from a list of URIs, was thinking of adding a PR for a cache + retry mechanism when I've got some time though.
