### ISSUE TITLE
Misleading error when using `-r` option

### ISSUE THREAD

**Issue by cojo** [samuelvanderwaal/metaboss#57]
Hi,

Thanks for this project!
Wanted to let you know I experienced a very strange / misleading error message this evening on 0.3.4...

When trying to `mint list` or `mint one` with the `-r` override:
```
metaboss mint list -r https://api.devnet.solana.com --keypair [redacted] --nft-data-dir [redacted] --primary-sale-happened  
[2022-01-10T02:50:54Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
[2022-01-10T02:50:54Z ERROR metaboss::mint] Failed to mint "0.json": Invalid Base58 string
[2022-01-10T02:50:54Z ERROR metaboss::mint] Failed to mint "1.json": Invalid Base58 string
Done!
```

But after messing around with it trying to figure out what was wrong with my key and / or address for over an hour, I tried removing various things from the command on a whim and this worked fine:
```
metaboss mint list --keypair [redacted] --nft-data-dir [redacted] --primary-sale-happened             
[2022-01-10T03:09:25Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
Tx id: [redacted]
Mint account: [redacted]
Tx id: [redacted]
Mint account:[redacted]
Done!
```

Not sure why this would matter / change things in a way that would break Pubkey processing / parsing?  I'm on macOS using zsh if it is maybe related to some weird CLI expansion thing?

Cheers!

**Comment by samuelvanderwaal** [comment]
Thanks for the report. Due to the way the RPC gets set up at the beginning of the command you have to pass it directly to the metaboss comand like this:

`metaboss -r https://api.devnet.solana.com mint list etc`

However, if you don't pass in a rpc option it tries to read whatever you have set for the RPC in your Solana CLI config ($HOME/.config/solana). That's why it worked the second time with no option passed in.

This is a bit awkward of an interface and the error reporting could definitely be better. Leave this issue open and I'll try to improve it.

**Comment by samuelvanderwaal** [comment]
You can see what your current config is set to with:

`solana config get`

**Comment by cojo** [comment]
Ahhh, I understand now.  Thank you for the explanation - very helpful! I will leave this open per your request, but let me know if you change your mind and I'm happy to close it as well. And thanks for the tip re: the free GenesysGo endpoint as well!

**Comment by samuelvanderwaal** [comment]
As of v0.3.5 you can pass the `-r` option in anywhere in the command list. 

So `metaboss mint list -r <rpc_url>` now works. :+1:
