### ISSUE TITLE
RPC response error -32002 with 0x36 error code

### ISSUE THREAD

**Issue by dinobby** [samuelvanderwaal/metaboss#59]
Hi, thanks for providing such convenient and amazing tools!

I've update the uri successfully by running
 `metaboss update uri -u <new_uri> -a <NFT mint address> -k <update_autority_keypair>`
and it worked just fine!

But since the number in the uri has changed, for example, from "My NFT # 100" to "My NFT # 101",
I also want to update the on-chain data so that they display consistently.

However, when I ran
`metaboss update data -n <new_data.json> -a <NFT mint address> -k <update_autority_keypair>` 
It constantly showing 0x36 error, which I found is the 
`CannotVerifyAnotherCreator: You cannot unilaterally verify another creator, they must sign"` error.

I've follow the format from here: https://metaboss.rs/update.html
and I also added the original creator as well as the candymachine, both of them set to be verified.

Any suggestion is appreciated!

**Comment by dinobby** [comment]
So I managed to modified the code in `update_metadata.rs` at line 207
`data.name = new_uri.to_string();` and I use the same command as update uri for doing it.
Work just fine though it's kind of lousy and experimental 🤣

**Comment by samuelvanderwaal** [comment]
> 've follow the format from here: https://metaboss.rs/update.html
and I also added the original creator as well as the candymachine, both of them set to be verified.

You can only verify for the creator that is the keypair you are running the command with. If you need to verify a different creator you have to run a separate command with that other keypair.
