### ISSUE TITLE
snapshot mints --update-authority empty json

### ISSUE THREAD

**Issue by selimerunkut** [samuelvanderwaal/metaboss#61]
I am trying to get the minter accounts of a collection.

The end goal is to determine who payed for the mint (versus the free mints).

Example NFT from the collection:
https://explorer.solana.com/address/EXpjsvvr83BfYc8oZ6buaaE5t9uF7ptki9haB1nWzmD1

this command should provide a the holders if I'm not mistaken:

`snapshot mints --update-authority 6d3XsxcLYnPKpgcspevQyCvkfPfuz2rcLjBkL1T9kaJY
`
or 
`snapshot holders --update-authority 6d3XsxcLYnPKpgcspevQyCvkfPfuz2rcLjBkL1T9kaJY`

I'm using this RPC endpoint:
json_rpc_url: "https://solana-api.projectserum.com"

The resulting file is always a empty json.

**Comment by samuelvanderwaal** [comment]
When I run `metaboss snapshot mints -u 6d3XsxcLYnPKpgcspevQyCvkfPfuz2rcLjBkL1T9kaJY` I get a file with 800+ mint accounts in it. Some things to check/try:

* Make sure you're running the command on a mainnet RPC node. Set your Solana config file to a mainnet node `solana config set --url <RPC_URL>` or pass one in: `metaboss -r <RPC_URL> snapshot mints`
* If you are sure you were on mainnet already, try the command again as Solana has been having severe congestion issues in the last 12-24 hours and it's possible something just went wrong.

**Comment by samuelvanderwaal** [comment]
Also, be aware that `update_authority` can be faked so be careful with this command.

**Comment by selimerunkut** [comment]
Thanks for the feedaback
tried with a quicknode RPC (payed plan) and getting the following error:
Error: error sending request for url (https://crimson-billowing-frost.solana-mainnet.quiknode.pro/...): operation timed out

Caused by:
    0: error sending request for url (https://crimson-billowing-frost.solana-mainnet.quiknode.pro/...): operation timed out
    1: operation timed out

What RPC service are you using @samuelvanderwaal ?

**Comment by selimerunkut** [comment]
Getting the same error as above for the example from the metabox doc:
https://metaboss.rs/examples.html
`metaboss mint one -k ~/.config/solana/devnet.json -d ./new_nft.json`

**Comment by samuelvanderwaal** [comment]
Try setting a longer timeout: 

`metaboss -t 90 snapshot mints etc`

The snapshot commands are taking longer than the default timeout of 60 seconds in some cases due to the increase in the number of accounts on Solana and congestion issues. 

I've increased the default timeout to 90 seconds in v0.3.5 so you could install that version if you don't want to have to set the timeout manually.

**Comment by samuelvanderwaal** [comment]
@selimerunkut did setting a longer timeout resolve your issue?

**Comment by selimerunkut** [comment]
Sorry a little bit late to reply.

Still getting a error:

```
metaboss -r https://...-frost.solana-mainnet.quiknode.pro/.../ -t 90 snapshot mints -u 6d3XsxcLYnPKpgcspevQyCvkfPfuz2rcLjBkL1T9kaJY
Error: error sending request for url (https://crimson-billowing-frost.solana-mainnet.quiknode.pro/4eea351d708b5f9a923f09790cbf919968a388c2/): connection closed before message completed

Caused by:
    0: error sending request for url (https://...-frost.solana-mainnet.quiknode.pro/.../): connection closed before message completed
    1: connection closed before message completed
```

**Comment by selimerunkut** [comment]
with -t 180 it worked 🎉🎉
