### ISSUE TITLE
No unverified metadata for this creator and candy machine

### ISSUE THREAD

**Issue by victorguima12** [samuelvanderwaal/metaboss#64]
![image](https://user-images.githubusercontent.com/73203416/151008312-5dfd3da7-e0b6-4c61-91d9-188a11be0d22.png)

![image](https://user-images.githubusercontent.com/73203416/151008351-cac50268-7b33-43d5-bd87-832f17de60ec.png)

When i run the metaboss sign all -k -c     with or without --v2 in the end, in both scenarios is says that theres no unverified metadata, but as you can see in the solana explorer still shows as unverified, even when i used this command for the first time it was the same response

**Comment by samuelvanderwaal** [comment]
Are you sure that the keypair you are using has the public key `7fXNuer5s...`?

**Comment by samuelvanderwaal** [comment]
@victorguima12 did you resolve this?

**Comment by KobeBlockify** [comment]
Having the same problem!

**Comment by samuelvanderwaal** [comment]
> Having the same problem!

Make sure you're signing with the creator's keypair as it may be different than the update authority and check that you're on the correct cluster: mainnet vs devnet. Without more details I can't really give any better advice.
