### ISSUE TITLE
RPC response error -32002 on Instruction 4

### ISSUE THREAD

**Issue by lukedupin** [samuelvanderwaal/metaboss#65]
I'm trying to test out minting NFTs on devnet. 

When I run
metaboss mint one -k my_solana_wallet.json --rpc https://api.devnet.solana.com  -d nft.json --receiver HarFxdtVoskW5JEbxwP7QAUZiWvuUnmUWdybYnURvvqa
[2022-01-28T05:51:50Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x26 [41 log messages]

me.json
```
{
    "name": "TestNFT1",
    "symbol": "TNFT",
    "uri": "https://arweave.net/FPGAv1XnyZidnqquOdEbSY6_ES735ckcDTdaAtI7GFw",
    "seller_fee_basis_points": 100,
    "creators": [
        {
            "address": "HarFxdtVoskW5JEbxwP7QAUZiWvuUnmUWdybYnURvvqa",
            "verified": false,
            "share": 100
        }
    ]
}

```

Am I missing something obvious?

**Comment by samuelvanderwaal** [comment]
The error you're getting is:

```bash
0x26: 
	Token Metadata            |	MustBeOneOfCreators: If using a creators array, you must be one of the creators listed
```

Currently, the `token-metadata` program requires the minting keypair to be in the creators array when creating a NFT. The easiest thing to do is just add the public key of your keypair into the creators array with a share of 0 (assuming you don't want it to get any royalties). You can set verified to `true` since it's the signing pair.

**Comment by lukedupin** [comment]
Thanks a bunch for your response. I'll give this a go and report back. These errors remind me of the old pic micro processor days working in assembly :-)

**Comment by samuelvanderwaal** [comment]
> Thanks a bunch for your response. I'll give this a go and report back. These errors remind me of the old pic micro processor days working in assembly :-)

I did a little programming of MSP430 microcontrollers in university and Solana programming definitely reminds me of that. Limited stack and heap, low-level byte programming and opaque errors. :-)

**Comment by lukedupin** [comment]
@samuelvanderwaal I finally got some time to start from scratch and follow your instructions. Yes that worked. Super happy!

Oh the MSP430, I never used it directly, but that chip's instruction set was the ASM target for my compiler class at University of Idaho.

Metaboss is a really great tool. Thanks a bunch for your help.
