### ISSUE TITLE
ubuntu binary for v0.3.5 corrupted

### ISSUE THREAD

**Issue by MarkSackerberg** [samuelvanderwaal/metaboss#66]
Hi Sam,
the zip file which contains the ubuntu binary for v0.3.5 is corrupted. v0.3.4 works though.

Can you maybe just trigger a new build or check the output?

Thank you!

**Comment by Apesonspace** [comment]
same problem

**Comment by samuelvanderwaal** [comment]
Thanks for the report! I re-ran the job and updated the Ubuntu binary. Let me know if you have any issues with it.
