### ISSUE TITLE
CHANGE FIRST VERIFIED CREATOR

### ISSUE THREAD

**Issue by lucastoian** [samuelvanderwaal/metaboss#67]
Is there any way to delete the first verified creator? (the candy machine)
I would like to make only my "DEVQ8KA.." as a verified creator so that I can see the nft minted by different candy machines as part of the same collection on Phantom wallet.
how can I do that?
![Screenshot (98)](https://user-images.githubusercontent.com/72082971/151564181-56f7d386-896a-4002-af3b-de9753417758.png)

**Comment by samuelvanderwaal** [comment]
Use the `update-data` command to change your creators array. You might consider just moving the candy machine down to a lower position in the array and keeping it verified rather than removing it entirely as once you remove it you can't get it back as a verified creator.

**Comment by lucastoian** [comment]
Ok but how can I change only the creators array without changing also the name, symbol, uri, ecc..
`{

  "creators": [
    {
      "address": "DEVQ8kAcY9MvqtmXar5HHKD1jgqrLvKAkfUTdDBnUfVo",
      "share": 10,
      "verified": true
    },
    {
      "address": "LCAUNGwsGB9gq3eaoz64M2SWXCqrNt35CVwZhz2gWPp",
      "share": 30,
      "verified": false
    },
    {
      "address": "5q8DAAkA4hmAk4rHpuoziZx1NDdRomstPFVygUJxG1mf",
      "share": 30,
      "verified": false
    },
    {
      "address": "DVRKuG1TqniCebrkwbkxdqHXtov8YRDPaDwtuEYePKUf",
      "share": 30,
      "verified": false
    }



  ],
  "name": "",
  "symbol": "",
  "uri": "",
  "ecc......"
    
}


`

**Comment by samuelvanderwaal** [comment]
You have to give Metaboss all the data in the `Data` struct right now. I'll probably add the ability to change certain fields by themselves in the next version of Metaboss, but in the meantime you can use the `decode` option to get the current data struct and then just update the creators array for each one and then pass that data into `update data` or `update data-all`.
