### ISSUE TITLE
RPC response error -32002: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

### ISSUE THREAD

**Issue by Jaycee12121** [samuelvanderwaal/metaboss#72]
Am i being dumb? 

![image](https://user-images.githubusercontent.com/98836751/152014589-fed8e950-b561-44ea-8873-1c5df709e386.png)

as you can see i have entered the withdraw code and it is clearly showing i have some rent to withdraw however it will not allow me. 

do i need to add funds to this wallet in order to withdraw more funds?

**Comment by samuelvanderwaal** [comment]
That means the wallet you are using to pay the transaction fees doesn't have any funds at it. Send some SOL to the keypair public address you're using. The candy machine account you're withdrawing from is different than the address you're using to sign the transaction.

**Comment by samuelvanderwaal** [comment]
@Jaycee12121 did this resolve your issue?
