### ISSUE TITLE
thread 'main' panicked at 'Unable to find libudev

### ISSUE THREAD

**Issue by ovuruska** [samuelvanderwaal/metaboss#73]
ERROR
---------
thread 'main' panicked at 'Unable to find libudev: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /home/oguz/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.3.2/build.rs:55:54
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

SOLUTION
------------
sudo apt-get -y install libudev-dev
sudo apt-get -y install pkg-config

**Comment by samuelvanderwaal** [comment]
This comes up enough I'll add something to the docs, thanks.

**Comment by samuelvanderwaal** [comment]
Added to the docs.
