### ISSUE TITLE
error: Found argument '--v2' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by ProjectSytras** [samuelvanderwaal/metaboss#75]
Hi!

When I want to run a snapshot, it show me 'error: Found argument '--v2' which wasn't expected, or isn't valid in this context'.

What should I do?

**Comment by samuelvanderwaal** [comment]
You're probably on an older version of Metaboss that doesn't support the `--v2` command. 

Install the binary for v0.3.6 or update your Rust install and install the latest version:

`rustup update`
`cargo install metaboss`

**Comment by ProjectSytras** [comment]
It works after I update it! Thank you
