### ISSUE TITLE
command "cargo install metaboss" error

### ISSUE THREAD

**Issue by Reolatas** [samuelvanderwaal/metaboss#77]
I tried install metaboss and got error :
 PS C:\Users\refex\Desktop\NFT R\v2\metaboss> cargo install metaboss
    Updating crates.io index
  Installing metaboss v0.3.7
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.136
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: could not compile `syn` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `metaboss v0.3.7`, intermediate artifacts can be found at `C:\Users\refex\AppData\Local\Temp\cargo-install1dy9Lq`

Caused by:
  build failed

![image](https://user-images.githubusercontent.com/99136085/152825960-91746be8-75c5-4163-957d-a0c010f44558.png)

**Comment by samuelvanderwaal** [comment]
```
note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option
```

Do you have one of these versions of Visual Studio installed?

**Comment by Reolatas** [comment]
> ```
> note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option
> ```
> 
> Do you have one of these versions of Visual Studio installed?

I have VS 2022 , VS 2019 and VSC

**Comment by samuelvanderwaal** [comment]
You're missing the linker needed to build Rust programs on Windows. Either use the pre-built Windows binary for the latest [release](https://github.com/samuelvanderwaal/metaboss/releases) or lookup how to setup Rust on Windows.

**Comment by ApesHunter231** [comment]
You have any solution for this?
