### ISSUE TITLE
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x36 [5 log messages]

### ISSUE THREAD

**Issue by ProjectSytras** [samuelvanderwaal/metaboss#78]
Hi! I was trying to run update my metadata on devnet to test it out first. However it came with an error "Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x36 [5 log messages]" 

I am not sure why I got the error. Please help me

**Comment by samuelvanderwaal** [comment]
The error is:

```
0x36: 
        Token Metadata            |     CannotVerifyAnotherCreator: You cannot unilaterally verify another creator, they must sign
```

Each individual creator can only verify themselves.

**Comment by ProjectSytras** [comment]
I'm sorry but i dont understand. What does it mean?

**Comment by samuelvanderwaal** [comment]
You're trying to set a creator as `verified` that is not the update authority keypair you are using to run `update`.

**Comment by ProjectSytras** [comment]
I just wanted to try and change the seller fee basis point, the rest of the creators are untouch. However the keypair that I'm using it different then the creator I have set.

**Comment by samuelvanderwaal** [comment]
Are you using the update authority keypair?

**Comment by ProjectSytras** [comment]
yes. Nvm i found the problem. I should not add in the candy machine id as the creator. However, that was what the template asked me to do, "address": "<YOUR_CANDY_MACHINE_ID>",

**Comment by samuelvanderwaal** [comment]
> yes. Nvm i found the problem. I should not add in the candy machine id as the creator. However, that was what the template asked me to do, "address": "<YOUR_CANDY_MACHINE_ID>",

That's just an example. What addresses you put in there depends on the details of what you're trying to do. Glad you figured it out though.
