### ISSUE TITLE
Snapshot Mints Error

### ISSUE THREAD

**Issue by simob2012** [samuelvanderwaal/metaboss#79]
Error : 
2022-02-08T11:34:46Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
Error: HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)

Caused by:
    HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)

**Comment by samuelvanderwaal** [comment]
That endpoint is now blocking calls to the `token-metadata` program so you need to use a different one. Check out this list to find a custom one: https://docs.metaplex.com/community#rpc

**Comment by simob2012** [comment]
how to use my custom RPC in this command "metaboss snapshot mints --candy-machine-id <CANDY_MACHINE_ID/CREATOR> --output <OUTPUT_DIR>"

**Comment by samuelvanderwaal** [comment]
> how to use my custom RPC in this command "metaboss snapshot mints --candy-machine-id <CANDY_MACHINE_ID/CREATOR> --output <OUTPUT_DIR>"

```
"metaboss snapshot mints -r <RPC_URL> --candy-machine-id <CANDY_MACHINE_ID/CREATOR> --output <OUTPUT_DIR>"
```

**Comment by simob2012** [comment]
error: Found argument '-r' which wasn't expected, or isn't valid in this context

USAGE:
    metaboss.exe snapshot mints [FLAGS] [OPTIONS]

For more information try --help
