### ISSUE TITLE
Error: error sending request for url <endpoint> operation timed out

### ISSUE THREAD

**Issue by noahh40** [samuelvanderwaal/metaboss#81]
What: 
I am trying to run this command: 
```bash
metaboss get_mints --candy-machine-id <CANDY_MACHINE_ID> -o <OUTPUT_DIRECTORY>
```
However, every time I run it a blank json file appears in the output directory. 
The candy machine ID I am using is 8RMqBV79p8sb51nMaKMWR94XKjUvD2kuUSAkpEJTmxyx (DeGods)

I have also tried running the following command: 
```
metaboss  -r https://api.mainnet-beta.solana.com get_mints --candy-machine-id 8RMqBV79p8sb51nMaKMWR94XKjUvD2kuUSAkpEJTmxyx  -o mints 
```
and I receive this error: 
```
 Error: HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)

Caused by:
    HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)
```

So I try using my own paid endpoint from quicknode and I get the following error: 
```
Error: error sending request for url<endpoint>: operation timed out

Caused by:
    0: error sending request for url (<endpoint>): operation timed out
    1: operation timed out
```

I checked the quicknode dashboard to make sure that the endpoint is working by looking at the metric dashboard: 
![telegram-cloud-photo-size-1-4906674401521543836-y](https://user-images.githubusercontent.com/26067212/153039513-e1e57801-ec12-487e-83ef-056950ae45fa.jpg)

And it looks like it is executing the requests at the time I run the command. 

Therefore, I am wondering if this is an issue with metaboss? Perhaps there is a way to extend the time out period? Any insight on this would be greatly appreciated. Thanks in advance.

**Comment by samuelvanderwaal** [comment]
You are using a very old version of Metaboss. Update to v0.3.7 to get a longer timeout by default or set it with `-t`:

`metaboss -t 90 snapshot mints`
