### ISSUE TITLE
Just owner wallet

### ISSUE THREAD

**Issue by ProjectSytras** [samuelvanderwaal/metaboss#82]
Hi this is not an issue but I just want to ask how can I snapshot just the owner wallet only? Just like the snapshot of mint account when it just list the mint account. I want it like that but for the holders. What should I change?

**Comment by samuelvanderwaal** [comment]
Metaboss doesn't currently have a command that does exactly that. You can get that info from the `snapshot holders` pretty easily. You can just write a simple Python script that gets all the "owners" and adds them to a set so there are no duplicates.
