### ISSUE TITLE
error: failed to compile `metaboss v0.4.1 (/mnt/c/Users/Abraham/code/Other/metaboss)`, intermediate artifacts can be found at `/mnt/c/Users/Abraham/code/Other/metaboss/target`

### ISSUE THREAD

**Issue by AbrahamDiaw** [samuelvanderwaal/metaboss#85]
Hello,
I have this error message that pops up after running the cmd 'cargo install --path ./' or 'cargo build --release'.
My environment is windows under wsl Ubuntu 20.04 LTS
My versions are : 
rustup 1.24.3 (ce5817a94 2021-05-31)
rustc => rustc 1.60.0-nightly (5d8767cb2 2022-02-12)
cargo => cargo 1.60.0-nightly (c082648 2022-02-08)

**Comment by samuelvanderwaal** [comment]
If you have Rust installed try installing directly from crates.io: `cargo install metaboss`. Otherwise, if you want to install from source use the latest stable build of Rust, not nightly.

**Comment by AbrahamDiaw** [comment]
Yes I have already tested this way but I have this error that poo failed to compile `metaboss v0.4.1`, intermediate artifacts can be found at `/tmp/cargo-installqUJbuM`

**Comment by samuelvanderwaal** [comment]
> Yes I have already tested this way but I have this error that poo failed to compile `metaboss v0.4.1`, intermediate artifacts can be found at `/tmp/cargo-installqUJbuM`

Hmm, sorry you're having issues. I don't have a Windows machine set up with WSL that I can try to duplicate this issue right now. Can you use one of the pre-built binaries? https://github.com/samuelvanderwaal/metaboss/releases

Otherwise make sure you have the `stable` version of Rust installed, not `nightly`.

**Comment by AbrahamDiaw** [comment]
Thanks! the solution was to change the environment but I still don't know the problem on wsl
