### ISSUE TITLE
link.exe not found

### ISSUE THREAD

**Issue by Radula73** [samuelvanderwaal/metaboss#90]
I get this error:

C:\Users\Nidza73\Desktop\solana>cargo download metaboss
error: no such subcommand: `download`

C:\Users\Nidza73\Desktop\solana>cargo install metaboss
    Updating crates.io index
  Installing metaboss v0.4.1
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.136
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: could not compile `syn` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `metaboss v0.4.1`, intermediate artifacts can be found at `C:\Users\Nidza73\AppData\Local\Temp\cargo-install1UU57K`

Caused by:
  build failed

**Comment by samuelvanderwaal** [comment]
When I get some time I'll look into why people are having linker issues on Windows. In the meantime, you can use a pre-built Windows binary: https://github.com/samuelvanderwaal/metaboss/releases

**Comment by poisendev91** [comment]
Please update your vs code and download these tools I have clicked on.
Also to get any more help join my discord
[THIRD EYE](https://discord.gg/UurzmJW3bC
![required components](https://user-images.githubusercontent.com/68282784/155329219-e4c1e3a3-5581-4238-898d-a9680097590e.PNG)
)
