### ISSUE TITLE
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: Program failed to complete [6 log messages]

### ISSUE THREAD

**Issue by Alaarhi** [samuelvanderwaal/metaboss#94]
Hey guys, I need your assistance with this error. 
I've been trying to update the external url of my minted token but I keep getting this. 
What am I doing wrong ? Also, how can I see the log files?
Thanks

**Comment by samuelvanderwaal** [comment]
> Hey guys, I need your assistance with this error. I've been trying to update the external url of my minted token but I keep getting this. What am I doing wrong ? Also, how can I see the log files? Thanks

What's the full command you are running?

**Comment by Alaarhi** [comment]
metaboss update data --keypair ~/.config/solana/mainnet.json --account <mintAcoount> --new-data-file ~/Desktop/nft/0.json

**Comment by samuelvanderwaal** [comment]
> metaboss update data --keypair ~/.config/solana/mainnet.json --account --new-data-file ~/Desktop/nft/0.json

You're missing the `account` parameter.

**Comment by Alaarhi** [comment]
I did add the value of my mint account! (apologies for not typing it here)

**Comment by samuelvanderwaal** [comment]
> I did add the value of my mint account! (apologies for not typing it here)

Ah, ok. Can you share the contents of the JSON file with me here or via Discord DM so I can check it? I suspect something is wrong with it.

**Comment by Alaarhi** [comment]
yes sure, What's your discord Id ?

**Comment by samuelvanderwaal** [comment]
archaeopteryx#7615

**Comment by Alaarhi** [comment]
I just added you! Asli#2275

**Comment by samuelvanderwaal** [comment]
Resolved in Discord DMs.

**Comment by janmallari** [comment]
I am having the same issue with this command;

> update uri
