### ISSUE TITLE
Error: network request failed after three attempts

### ISSUE THREAD

**Issue by kcc0** [samuelvanderwaal/metaboss#95]
Hi there,

Just did a plain and simple `metaboss decode mint --account <<CANDY_MACHINE_ID>>` after installation using cargo.
Was there a step that I skipped because I'm not able to use this tool at all right now. 

This is the error I get: `Error: network request failed after three attempts`

Any help here is appreciated.

Thanks!

**Comment by samuelvanderwaal** [comment]
> Hi there,
> 
> Just did a plain and simple `metaboss decode mint --account <<CANDY_MACHINE_ID>>` after installation using cargo. Was there a step that I skipped because I'm not able to use this tool at all right now.
> 
> This is the error I get: `Error: network request failed after three attempts`
> 
> Any help here is appreciated.
> 
> Thanks!

Metaboss doesn't support decoding candy machine data. `decode` is for getting the Metadata from a mint account. https://metaboss.rs/decode

**Comment by kcc0** [comment]
> > Hi there,
> > Just did a plain and simple `metaboss decode mint --account <<CANDY_MACHINE_ID>>` after installation using cargo. Was there a step that I skipped because I'm not able to use this tool at all right now.
> > This is the error I get: `Error: network request failed after three attempts`
> > Any help here is appreciated.
> > Thanks!
> 
> Metaboss doesn't support decoding candy machine data. `decode` is for getting the Metadata from a mint account. https://metaboss.rs/decode

> 

My apologies ser.

I, in fact, did use the mint account as well. Here's the log-trace from my request.
Replaced it with the token account as well but that didn't seem to help.

Any help here is appreciated.

```
➜  nft-bread-heads git:(main) ✗ metaboss decode mint --log-level trace -a <<mint_account_public_key>>
[2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] (ThreadId(1)) park without timeout
[2022-02-24T17:20:35Z TRACE mio::poll] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
[2022-02-24T17:20:35Z TRACE reqwest::blocking::client] (ThreadId(2)) start runtime::block_on
[2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999966208s
[2022-02-24T17:20:35Z DEBUG reqwest::connect] starting new connection: https://misty-fragrant-sky.solana-mainnet.quiknode.pro/
[2022-02-24T17:20:35Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:38Z TRACE want] signal found waiting giver, notifying
[2022-02-24T17:20:38Z TRACE want] poll_want: taker wants!
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:38Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
[2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999997333s
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:38Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
[2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:38Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
[2022-02-24T17:20:38Z TRACE want] signal: Want
[2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999983834s
[2022-02-24T17:20:39Z TRACE want] signal: Want
[2022-02-24T17:20:39Z TRACE want] signal: Want
[2022-02-24T17:20:39Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
[2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:39Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
[2022-02-24T17:20:39Z TRACE want] signal: Want
[2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999983375s
[2022-02-24T17:20:40Z TRACE want] signal: Want
[2022-02-24T17:20:40Z TRACE want] signal: Want
[2022-02-24T17:20:40Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
[2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:40Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
[2022-02-24T17:20:40Z TRACE want] signal: Want
[2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999994708s
[2022-02-24T17:20:41Z TRACE want] signal: Want
[2022-02-24T17:20:41Z TRACE want] signal: Want
[2022-02-24T17:20:41Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
[2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-24T17:20:41Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
[2022-02-24T17:20:41Z TRACE want] signal: Want
[2022-02-24T17:20:41Z TRACE reqwest::blocking::client] closing runtime thread (ThreadId(2))
[2022-02-24T17:20:41Z TRACE reqwest::blocking::client] signaled close for runtime thread (ThreadId(2))
[2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) Receiver is shutdown
[2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) end runtime::block_on
[2022-02-24T17:20:41Z TRACE mio::poll] deregistering event source from poller
[2022-02-24T17:20:41Z TRACE want] signal: Closed
[2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) finished
[2022-02-24T17:20:41Z TRACE reqwest::blocking::client] closed runtime thread (ThreadId(2))
Error: network request failed after three attempts
```

**Comment by tomspleesters** [comment]
I also bump on this exact issue.

**Comment by samuelvanderwaal** [comment]
> > > Hi there,
> > > Just did a plain and simple `metaboss decode mint --account <<CANDY_MACHINE_ID>>` after installation using cargo. Was there a step that I skipped because I'm not able to use this tool at all right now.
> > > This is the error I get: `Error: network request failed after three attempts`
> > > Any help here is appreciated.
> > > Thanks!
> > 
> > 
> > Metaboss doesn't support decoding candy machine data. `decode` is for getting the Metadata from a mint account. https://metaboss.rs/decode
> 
> > 
> 
> My apologies ser.
> 
> I, in fact, did use the mint account as well. Here's the log-trace from my request. Replaced it with the token account as well but that didn't seem to help.
> 
> Any help here is appreciated.
> 
> ```
> ➜  nft-bread-heads git:(main) ✗ metaboss decode mint --log-level trace -a <<mint_account_public_key>>
> [2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] (ThreadId(1)) park without timeout
> [2022-02-24T17:20:35Z TRACE mio::poll] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
> [2022-02-24T17:20:35Z TRACE reqwest::blocking::client] (ThreadId(2)) start runtime::block_on
> [2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999966208s
> [2022-02-24T17:20:35Z DEBUG reqwest::connect] starting new connection: https://misty-fragrant-sky.solana-mainnet.quiknode.pro/
> [2022-02-24T17:20:35Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:38Z TRACE want] signal found waiting giver, notifying
> [2022-02-24T17:20:38Z TRACE want] poll_want: taker wants!
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:38Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999997333s
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:38Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:38Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> [2022-02-24T17:20:38Z TRACE want] signal: Want
> [2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999983834s
> [2022-02-24T17:20:39Z TRACE want] signal: Want
> [2022-02-24T17:20:39Z TRACE want] signal: Want
> [2022-02-24T17:20:39Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> [2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:39Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> [2022-02-24T17:20:39Z TRACE want] signal: Want
> [2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999983375s
> [2022-02-24T17:20:40Z TRACE want] signal: Want
> [2022-02-24T17:20:40Z TRACE want] signal: Want
> [2022-02-24T17:20:40Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> [2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:40Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> [2022-02-24T17:20:40Z TRACE want] signal: Want
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999994708s
> [2022-02-24T17:20:41Z TRACE want] signal: Want
> [2022-02-24T17:20:41Z TRACE want] signal: Want
> [2022-02-24T17:20:41Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] wait at most 90s
> [2022-02-24T17:20:41Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> [2022-02-24T17:20:41Z TRACE want] signal: Want
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] closing runtime thread (ThreadId(2))
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] signaled close for runtime thread (ThreadId(2))
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) Receiver is shutdown
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) end runtime::block_on
> [2022-02-24T17:20:41Z TRACE mio::poll] deregistering event source from poller
> [2022-02-24T17:20:41Z TRACE want] signal: Closed
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) finished
> [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] closed runtime thread (ThreadId(2))
> Error: network request failed after three attempts
> ```

Make sure your RPC is on the same cluster as the mint account you're trying to decode (mainnet vs devnet). Otherwise, can you post the mint account you're trying to decode so I can try it on my end?

**Comment by kcc0** [comment]
> > > > Hi there,
> > > > Just did a plain and simple `metaboss decode mint --account <<CANDY_MACHINE_ID>>` after installation using cargo. Was there a step that I skipped because I'm not able to use this tool at all right now.
> > > > This is the error I get: `Error: network request failed after three attempts`
> > > > Any help here is appreciated.
> > > > Thanks!
> > > 
> > > 
> > > Metaboss doesn't support decoding candy machine data. `decode` is for getting the Metadata from a mint account. https://metaboss.rs/decode
> > 
> > 
> > > 
> > 
> > 
> > My apologies ser.
> > I, in fact, did use the mint account as well. Here's the log-trace from my request. Replaced it with the token account as well but that didn't seem to help.
> > Any help here is appreciated.
> > ```
> > ➜  nft-bread-heads git:(main) ✗ metaboss decode mint --log-level trace -a <<mint_account_public_key>>
> > [2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] (ThreadId(1)) park without timeout
> > [2022-02-24T17:20:35Z TRACE mio::poll] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
> > [2022-02-24T17:20:35Z TRACE reqwest::blocking::client] (ThreadId(2)) start runtime::block_on
> > [2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:35Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999966208s
> > [2022-02-24T17:20:35Z DEBUG reqwest::connect] starting new connection: https://misty-fragrant-sky.solana-mainnet.quiknode.pro/
> > [2022-02-24T17:20:35Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:38Z TRACE want] signal found waiting giver, notifying
> > [2022-02-24T17:20:38Z TRACE want] poll_want: taker wants!
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:38Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> > [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999997333s
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:38Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> > [2022-02-24T17:20:38Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:38Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> > [2022-02-24T17:20:38Z TRACE want] signal: Want
> > [2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999983834s
> > [2022-02-24T17:20:39Z TRACE want] signal: Want
> > [2022-02-24T17:20:39Z TRACE want] signal: Want
> > [2022-02-24T17:20:39Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> > [2022-02-24T17:20:39Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:39Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> > [2022-02-24T17:20:39Z TRACE want] signal: Want
> > [2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999983375s
> > [2022-02-24T17:20:40Z TRACE want] signal: Want
> > [2022-02-24T17:20:40Z TRACE want] signal: Want
> > [2022-02-24T17:20:40Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> > [2022-02-24T17:20:40Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:40Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> > [2022-02-24T17:20:40Z TRACE want] signal: Want
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999994708s
> > [2022-02-24T17:20:41Z TRACE want] signal: Want
> > [2022-02-24T17:20:41Z TRACE want] signal: Want
> > [2022-02-24T17:20:41Z DEBUG reqwest::async_impl::client] response '200 OK' for <<custom_rpc_URL>>
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::wait] wait at most 90s
> > [2022-02-24T17:20:41Z TRACE solana_client::rpc_client] Response account 4Cmuv511hc9esPunUJyaks5bGVbDovnCY2qKdfxGhbU7 None
> > [2022-02-24T17:20:41Z TRACE want] signal: Want
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] closing runtime thread (ThreadId(2))
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] signaled close for runtime thread (ThreadId(2))
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) Receiver is shutdown
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) end runtime::block_on
> > [2022-02-24T17:20:41Z TRACE mio::poll] deregistering event source from poller
> > [2022-02-24T17:20:41Z TRACE want] signal: Closed
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] (ThreadId(2)) finished
> > [2022-02-24T17:20:41Z TRACE reqwest::blocking::client] closed runtime thread (ThreadId(2))
> > Error: network request failed after three attempts
> > ```
> 
> Make sure your RPC is on the same cluster as the mint account you're trying to decode (mainnet vs devnet). Otherwise, can you post the mint account you're trying to decode so I can try it on my end?

Yes sir! That would help a lot!
Thank you!

Mint wallet address (public key) - 7LmXpzerpTMkhd6nJWHkmD55nYJGRDd8J3KvWpMH9cEs

**Comment by kcc0** [comment]
> `7LmXpzerpTMkhd6nJWHkmD55nYJGRDd8J3KvWpMH9cEs` isn't a NFT mint account it looks like a normal wallet account. What are you trying to decode?

Ok, thanks for that.
I found out what I was doing wrong based on your response.

I was using the seller wallet account instead of the minted NFT token account.
Guess I understand how to use this now.

Apologies for the confusion. And thanks for your help.
