### ISSUE TITLE
Mint with Latest Metadata Standard

### ISSUE THREAD

**Issue by kevinrodriguez-io** [samuelvanderwaal/metaboss#99]
Getting this program logs when I mint with `metaboss`:
```
> Program log: (Deprecated as of 1.1.0) Instruction: Create Metadata Accounts
```

Pretty much opening the issue to track advance on this; If I find some spare time I may add it.

**Comment by samuelvanderwaal** [comment]
I have a release coming out in a few days with some minor improvements (0.5.0) and then the next one will have token standard 1.1.0 updates (0.6.0). Right now this doesn't hurt anything though. The endpoint is deprecated but it still mints valid Metaplex NFTs. If you get time to create a PR to use the new `create_metadata` handler that would be great though!

**Comment by samuelvanderwaal** [comment]
v0.6.0 removes the deprecated warning even though it doesn't have collection and uses support in minting yet.
